version: "3.8"

services:

  master:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-master
    command: "master -ip=master -port=9333"
    ports:
      - "9333:9333"
      - "19333:19333"
    volumes:
      - C:/seaweedfs/master:/data
    networks:
      - seaweed

  volume:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-volume
    command: "volume -mserver=master:9333 -dir=/data -port=8080"
    depends_on:
      - master
    volumes:
      - C:/seaweedfs/data:/data
    ports:
      - "8080:8080"
    networks:
      - seaweed

  filer:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-filer
    command: "filer -master=master:9333 -port=8888"
    depends_on:
      - master
      - volume
    volumes:
      - C:/seaweedfs/filer:/data
    ports:
      - "8888:8888"
    networks:
      - seaweed

  s3:
    image: chrislusf/seaweedfs:latest
    container_name: seaweed-s3
    command: "s3 -filer=filer:8888 -port=8333"
    depends_on:
      - filer
    ports:
      - "8333:8333"
    networks:
      - seaweed

networks:
  seaweed:
    driver: bridge