"""
LogHawk Stage B - Isolation Forest Anomaly Detection

Consumes the feature dataset generated by Stage A.

Input:
    data/features/log_features/*.parquet

Output:
    data/anomalies/isolation_forest_results.parquet

The model is trained using a normal baseline and then used to
calculate anomaly scores for all feature windows.
"""

from pathlib import Path

import joblib
import numpy as np
import pandas as pd

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

import loghawk.config as config

# ============================================================
# Configuration
# ============================================================

INPUT_PATH = config.LH_FEATURE_DIR
OUTPUT_PATH = config.LH_ANOMALY_DETECTION_DIR / "isolation_forest_results.parquet"

MODEL_PATH = config.LH_MODEL_DIR / "isolation_forest.joblib"
SCALER_PATH = config.LH_MODEL_DIR / "isolation_scaler.joblib"


# ------------------------------------------------------------
# Number of baseline samples used to train the model.
#
# The baseline should represent NORMAL production behaviour.
# ------------------------------------------------------------

BASELINE_RATIO = 0.70

MIN_BASELINE_ROWS = 20


# ------------------------------------------------------------
# Isolation Forest configuration
# ------------------------------------------------------------

CONTAMINATION = 0.05

N_ESTIMATORS = 200

RANDOM_STATE = 42


# ============================================================
# Feature columns generated by Stage A
# ============================================================

FEATURE_COLUMNS = [
    "total_log_count",
    "info_count",
    "warning_count",
    "error_count",
    "http_4xx_count",
    "http_5xx_count",
    "timeout_count",
    "connection_error_count",
    "authentication_failure_count",
    "unique_exception_count",
    "unique_error_message_count",
    "error_rate",
    "warning_rate",
    "http_5xx_rate",
    "timeout_rate",
]


# ============================================================
# Utility functions
# ============================================================

def validate_features(df: pd.DataFrame):
    """
    Verify that all Stage A feature columns exist.
    """

    missing = [
        column
        for column in FEATURE_COLUMNS
        if column not in df.columns
    ]

    if missing:
        raise ValueError(
            f"Missing required feature columns: {missing}"
        )


def load_features():

    print(f"Loading Stage A features from: {INPUT_PATH}")

    df = pd.read_parquet(INPUT_PATH)

    print(f"Loaded {len(df):,} feature rows")

    validate_features(df)

    return df


def clean_features(df):

    """
    Clean numerical feature data before ML processing.
    """

    df = df.copy()

    # Replace +/- infinity
    df[FEATURE_COLUMNS] = (
        df[FEATURE_COLUMNS]
        .replace([np.inf, -np.inf], np.nan)
    )

    # Replace missing values
    df[FEATURE_COLUMNS] = (
        df[FEATURE_COLUMNS]
        .fillna(0)
    )

    return df


# ============================================================
# Baseline selection
# ============================================================

def select_normal_baseline(df):
    """
    Select the earliest portion of the dataset as the normal baseline.

    Stage A uses 'timestamp' as the 1-minute aggregation timestamp.
    """

    if "timestamp" not in df.columns:
        raise ValueError(
            "Stage A feature dataset must contain a 'timestamp' column."
        )

    df = df.sort_values("timestamp").reset_index(drop=True)

    baseline_size = max(
        int(len(df) * BASELINE_RATIO),
        MIN_BASELINE_ROWS
    )

    # Never use more rows than actually exist
    baseline_size = min(baseline_size, len(df))

    baseline = df.iloc[:baseline_size].copy()

    print(f"Selected {len(baseline)} rows as normal baseline")

    return baseline

# ============================================================
# Train Isolation Forest
# ============================================================

def train_model(baseline):

    print("Training Isolation Forest...")

    X_train = baseline[FEATURE_COLUMNS].values

    # --------------------------------------------------------
    # Standardize features.
    #
    # This makes features with very different numeric scales
    # easier to use together.
    # --------------------------------------------------------

    scaler = StandardScaler()

    X_train_scaled = scaler.fit_transform(X_train)

    model = IsolationForest(
        n_estimators=N_ESTIMATORS,
        contamination=CONTAMINATION,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )

    model.fit(X_train_scaled)

    print("Isolation Forest training completed")

    return model, scaler


# ============================================================
# Calculate anomaly score
# ============================================================

def calculate_scores(df, model, scaler):

    X = df[FEATURE_COLUMNS].values

    X_scaled = scaler.transform(X)

    # --------------------------------------------------------
    # IsolationForest.score_samples()
    #
    # Higher = more normal
    # Lower  = more anomalous
    #
    # We invert it so that:
    #
    # higher anomaly_score = more anomalous
    # --------------------------------------------------------

    raw_scores = model.score_samples(X_scaled)

    anomaly_score = -raw_scores

    df["anomaly_score"] = anomaly_score

    # sklearn's prediction:
    #
    #  1  = normal
    # -1  = anomaly
    #

    predictions = model.predict(X_scaled)

    df["is_anomaly"] = predictions == -1

    return df


# ============================================================
# Convert anomaly score into severity
# ============================================================

def calculate_severity(df):

    """
    Convert Isolation Forest anomaly results into operational severity.

    Important design rule:
        NORMAL is assigned to every record that Isolation Forest
        classified as normal.

        WARNING / HIGH / CRITICAL are assigned only to records
        that Isolation Forest classified as anomalous.

    This keeps anomaly detection separate from severity:

        is_anomaly = "Did the ML model detect unusual behaviour?"
        severity   = "How severe is that detected anomaly?"

    The initial severity thresholds are relative to the anomaly
    scores of detected anomalies and should be tuned using real
    LogHawk production data.
    """

    df = df.copy()
    df["severity"] = "NORMAL"

    anomaly_mask = df["is_anomaly"]

    if not anomaly_mask.any():
        return df

    anomaly_scores = df.loc[anomaly_mask, "anomaly_score"]

    q50 = anomaly_scores.quantile(0.50)
    q90 = anomaly_scores.quantile(0.90)
    q99 = anomaly_scores.quantile(0.99)

    anomaly_conditions = [
        anomaly_scores >= q99,
        anomaly_scores >= q90,
        anomaly_scores >= q50,
    ]

    anomaly_choices = [
        "CRITICAL",
        "HIGH",
        "WARNING",
    ]

    df.loc[anomaly_mask, "severity"] = np.select(
        anomaly_conditions,
        anomaly_choices,
        default="WARNING",
    )

    return df


# ============================================================
# Add human-readable explanation
# ============================================================

def generate_reason(row):

    reasons = []

    if row["error_rate"] > 0:
        reasons.append(
            f"error_rate={row['error_rate']:.2f}"
        )

    if row["http_5xx_count"] > 0:
        reasons.append(
            f"http_5xx={int(row['http_5xx_count'])}"
        )

    if row["timeout_count"] > 0:
        reasons.append(
            f"timeouts={int(row['timeout_count'])}"
        )

    if row["connection_error_count"] > 0:
        reasons.append(
            f"connection_errors="
            f"{int(row['connection_error_count'])}"
        )

    if row["authentication_failure_count"] > 0:
        reasons.append(
            f"auth_failures="
            f"{int(row['authentication_failure_count'])}"
        )

    if row["unique_exception_count"] > 0:
        reasons.append(
            f"unique_exceptions="
            f"{int(row['unique_exception_count'])}"
        )

    if not reasons:
        return "No significant anomaly indicators"

    return "; ".join(reasons)


# ============================================================
# Save model
# ============================================================

def save_model(model, scaler):

    Path(MODEL_PATH).parent.mkdir(
        parents=True,
        exist_ok=True
    )

    joblib.dump(model, MODEL_PATH)

    joblib.dump(scaler, SCALER_PATH)

    print(f"Model saved: {MODEL_PATH}")
    print(f"Scaler saved: {SCALER_PATH}")


# ============================================================
# Save anomaly results
# ============================================================

def save_results(df):

    Path(OUTPUT_PATH).parent.mkdir(
        parents=True,
        exist_ok=True
    )

    df.to_parquet(
        OUTPUT_PATH,
        index=False
    )

    print(
        f"Anomaly results saved to: {OUTPUT_PATH}"
    )


# ============================================================
# Main
# ============================================================

def main():

    print("=" * 70)
    print("LogHawk Stage B - Isolation Forest")
    print("=" * 70)

    # --------------------------------------------------------
    # 1. Load Stage A dataset
    # --------------------------------------------------------

    df = load_features()

    # --------------------------------------------------------
    # 2. Clean features
    # --------------------------------------------------------

    df = clean_features(df)

    # --------------------------------------------------------
    # 3. Select NORMAL baseline
    # --------------------------------------------------------

    baseline = select_normal_baseline(df)

    # --------------------------------------------------------
    # 4. Train model
    # --------------------------------------------------------

    model, scaler = train_model(baseline)

    # --------------------------------------------------------
    # 5. Score every feature window
    # --------------------------------------------------------

    df = calculate_scores(
        df,
        model,
        scaler
    )

    # --------------------------------------------------------
    # 6. Calculate severity
    # --------------------------------------------------------

    df = calculate_severity(df)

    # --------------------------------------------------------
    # 7. Generate explanation
    # --------------------------------------------------------

    df["reason"] = df.apply(
        generate_reason,
        axis=1
    )

    # --------------------------------------------------------
    # 8. Save model
    # --------------------------------------------------------

    save_model(
        model,
        scaler
    )

    # --------------------------------------------------------
    # 9. Save anomaly results
    # --------------------------------------------------------

    save_results(df)

    # --------------------------------------------------------
    # 10. Print summary
    # --------------------------------------------------------

    print()
    print("=" * 70)
    print("ANOMALY SUMMARY")
    print("=" * 70)

    print(
        df["severity"]
        .value_counts()
        .to_string()
    )

    print()
    print(
        "Detected anomalies:",
        int(df["is_anomaly"].sum())
    )

    print()
    print("Top anomalies:")

    columns = [
        "timestamp",
        "service",
        "anomaly_score",
        "severity",
        "reason",
    ]

    anomaly_results = (
        df[df["is_anomaly"]]
        .sort_values(
            "anomaly_score",
            ascending=False
        )[columns]
        .head(20)
    )

    if anomaly_results.empty:
        print("No anomalies detected.")
    else:
        print(anomaly_results.to_string(index=False))

    print()
    print("Stage B completed successfully.")


if __name__ == "__main__":
    main()