"""
LogHawk Stage B - Isolation Forest Anomaly Detection with SynapseML

Consumes the feature dataset generated by Stage A and performs
Isolation Forest anomaly detection entirely with Apache Spark and
Microsoft SynapseML.

Input:
    data/features/log_features/*.parquet

Output:
    data/anomalies/isolation_forest_results.parquet

Model:
    data/models/isolation_forest_synapseml

Important:
    This implementation intentionally does NOT use pandas,
    scikit-learn, numpy, StandardScaler, or joblib.

    Feature processing, training, scoring, severity calculation,
    and result persistence are performed with Spark/SynapseML.
"""

from pathlib import Path

from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F
from pyspark.sql.window import Window
from pyspark.ml import Pipeline
from pyspark.ml.feature import VectorAssembler
from synapse.ml.isolationforest import IsolationForest
import loghawk.config as config

import os
import sys

os.environ["JAVA_HOME"] = r"C:\\jdk-17"
os.environ["HADOOP_HOME"] = r"C:\\hadoop"
os.environ["SPARK_LOCAL_IP"] = "127.0.0.1"
os.environ["SPARK_LOCAL_HOSTNAME"] = "localhost"
os.environ["PYSPARK_PYTHON"] = sys.executable
os.environ["PYSPARK_DRIVER_PYTHON"] = sys.executable
os.environ["PATH"] = (
    r"C:\\jdk-17\\bin;"
    r"C:\\hadoop\\bin;"
    + os.environ.get("PATH", "")
)


# ============================================================
# Configuration
# ============================================================

INPUT_PATH = str(config.LH_FEATURE_DIR)
OUTPUT_PATH = str(
    config.LH_ANOMALY_DETECTION_DIR
    / "isolation_forest_results.parquet"
)

MODEL_PATH = str(
    config.LH_MODEL_DIR
    / "isolation_forest_synapseml"
)


# ------------------------------------------------------------
# Normal baseline configuration
# ------------------------------------------------------------

BASELINE_RATIO = 0.70
MIN_BASELINE_ROWS = 20


# ------------------------------------------------------------
# SynapseML Isolation Forest configuration
# ------------------------------------------------------------

CONTAMINATION = 0.05
N_ESTIMATORS = 200
MAX_SAMPLES = 256
MAX_FEATURES = 1.0
BOOTSTRAP = False
RANDOM_SEED = 42
CONTAMINATION_ERROR = 0.0005


# ============================================================
# Feature columns generated by Stage A
# ============================================================

FEATURE_COLUMNS = [
    "total_log_count",
    "info_count",
    "warning_count",
    "error_count",
    "http_4xx_count",
    "http_5xx_count",
    "timeout_count",
    "connection_error_count",
    "authentication_failure_count",
    "unique_exception_count",
    "unique_error_message_count",
    "error_rate",
    "warning_rate",
    "http_5xx_rate",
    "timeout_rate",
]


# ============================================================
# Spark session
# ============================================================

def create_spark_session():
    return (
        SparkSession.builder
        .appName("LogHawk-Stage-B-IsolationForest-SynapseML")
        .master("local[1]")
        .config("spark.driver.host", "127.0.0.1")
        .config("spark.driver.bindAddress", "127.0.0.1")
        .config("spark.executor.instances", "1")
        .config("spark.executor.cores", "1")
        .config("spark.default.parallelism", "1")
        .config("spark.sql.shuffle.partitions", "1")
        .config("spark.local.dir", r"C:\tmp\spark")
        .config("spark.jars.packages", "com.microsoft.azure:synapseml_2.13:1.1.3-spark4.1")
        .config("spark.sql.parquet.enableVectorizedReader", "false")
        .getOrCreate()
    )

# ============================================================
# Utility functions
# ============================================================

def validate_features(df: DataFrame):
    """Verify that all Stage A feature columns exist."""

    required_columns = ["timestamp", "service"] + FEATURE_COLUMNS

    missing = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing:
        raise ValueError(
            f"Missing required Stage A columns: {missing}"
        )


def load_features(spark):
    """Load Stage A Parquet features using Spark."""

    print(f"Loading Stage A features from: {INPUT_PATH}")

    df = spark.read.parquet(INPUT_PATH)

    row_count = df.count()

    print(f"Loaded {row_count:,} feature rows")

    validate_features(df)

    return df


def clean_features(df: DataFrame):
    """
    Clean numerical feature columns using Spark expressions.

    No pandas/numpy operations are used.
    """

    for column in FEATURE_COLUMNS:
        df = df.withColumn(
            column,
            F.col(column).cast("double")
        )

        # Replace NULL, NaN, +Infinity and -Infinity with zero.
        df = df.withColumn(
            column,
            F.when(
                F.col(column).isNull()
                | F.isnan(F.col(column))
                | (F.col(column) == float("inf"))
                | (F.col(column) == float("-inf")),
                F.lit(0.0),
            ).otherwise(F.col(column))
        )

    return df


# ============================================================
# Baseline selection
# ============================================================

def select_normal_baseline(df: DataFrame):
    """
    Select the earliest portion of the dataset as the normal baseline.

    Stage A uses 'timestamp' as the 1-minute aggregation timestamp.

    This retains the original Stage B strategy. For production,
    the baseline should eventually be selected from an explicitly
    known NORMAL time range rather than assuming the earliest data
    is normal.
    """

    if "timestamp" not in df.columns:
        raise ValueError(
            "Stage A feature dataset must contain a 'timestamp' column."
        )

    df = df.orderBy("timestamp")

    total_rows = df.count()

    baseline_size = max(
        int(total_rows * BASELINE_RATIO),
        MIN_BASELINE_ROWS,
    )

    baseline_size = min(baseline_size, total_rows)

    baseline = df.limit(baseline_size)

    print(f"Selected {baseline_size:,} rows as normal baseline")

    return baseline


# ============================================================
# Train SynapseML Isolation Forest
# ============================================================

def train_model(baseline):
    """Train Microsoft SynapseML Isolation Forest using Spark."""

    print("Training SynapseML Isolation Forest...")

    assembler = VectorAssembler(
        inputCols=FEATURE_COLUMNS,
        outputCol="features",
        handleInvalid="keep",
    )

    isolation_forest = (
        IsolationForest()
        .setNumEstimators(N_ESTIMATORS)
        .setBootstrap(BOOTSTRAP)
        .setMaxSamples(MAX_SAMPLES)
        .setMaxFeatures(MAX_FEATURES)
        .setFeaturesCol("features")
        .setPredictionCol("predictedLabel")
        .setScoreCol("outlierScore")
        .setContamination(CONTAMINATION)
        .setContaminationError(CONTAMINATION_ERROR)
        .setRandomSeed(RANDOM_SEED)
    )

    pipeline = Pipeline(
        stages=[assembler, isolation_forest]
    )

    model = pipeline.fit(baseline)

    print("SynapseML Isolation Forest training completed")

    return model


# ============================================================
# Calculate anomaly score
# ============================================================

def calculate_scores(df: DataFrame, model):
    """
    Score every feature window with the trained SynapseML model.

    SynapseML produces:
        predictedLabel - 1 for anomaly, 0 for normal
        outlierScore   - Isolation Forest outlier score

    The exact score scale is model-specific, so it is retained as
    produced by SynapseML rather than negated like sklearn's
    score_samples().
    """

    scored = model.transform(df)

    scored = scored.withColumn(
        "is_anomaly",
        F.col("predictedLabel") == F.lit(1.0)
    )

    scored = scored.withColumn(
        "anomaly_score",
        F.col("outlierScore").cast("double")
    )

    return scored


# ============================================================
# Convert anomaly score into severity
# ============================================================

def calculate_severity(df: DataFrame):
    """
    Convert SynapseML anomaly results into operational severity.

    Design rule:
        NORMAL is assigned to records that SynapseML classifies as
        normal.

        WARNING / HIGH / CRITICAL are assigned only to records that
        SynapseML classifies as anomalous.

    Thresholds are calculated only among detected anomalies.
    """

    df = df.withColumn(
        "severity",
        F.lit("NORMAL")
    )

    anomaly_df = df.filter(F.col("is_anomaly"))

    if anomaly_df.limit(1).count() == 0:
        return df

    quantiles = anomaly_df.approxQuantile(
        "anomaly_score",
        [0.50, 0.90, 0.99],
        0.01,
    )

    q50, q90, q99 = quantiles

    severity = (
        F.when(F.col("anomaly_score") >= q99, "CRITICAL")
        .when(F.col("anomaly_score") >= q90, "HIGH")
        .when(F.col("anomaly_score") >= q50, "WARNING")
        .otherwise("WARNING")
    )

    return df.withColumn(
        "severity",
        F.when(F.col("is_anomaly"), severity)
        .otherwise(F.lit("NORMAL"))
    )


# ============================================================
# Add human-readable explanation
# ============================================================

def generate_reason(df: DataFrame):
    """
    Generate a Spark-native human-readable explanation.
    """

    reason_parts = [
        F.when(
            F.col("error_rate") > 0,
            F.format_string(
                "error_rate=%.2f",
                F.col("error_rate")
            )
        ),
        F.when(
            F.col("http_5xx_count") > 0,
            F.format_string(
                "http_5xx=%d",
                F.col("http_5xx_count").cast("long")
            )
        ),
        F.when(
            F.col("timeout_count") > 0,
            F.format_string(
                "timeouts=%d",
                F.col("timeout_count").cast("long")
            )
        ),
        F.when(
            F.col("connection_error_count") > 0,
            F.format_string(
                "connection_errors=%d",
                F.col("connection_error_count").cast("long")
            )
        ),
        F.when(
            F.col("authentication_failure_count") > 0,
            F.format_string(
                "auth_failures=%d",
                F.col("authentication_failure_count").cast("long")
            )
        ),
        F.when(
            F.col("unique_exception_count") > 0,
            F.format_string(
                "unique_exceptions=%d",
                F.col("unique_exception_count").cast("long")
            )
        ),
    ]

    df = df.withColumn(
        "reason",
        F.coalesce(
            F.concat_ws("; ", *reason_parts),
            F.lit("No significant anomaly indicators")
        )
    )

    return df


# ============================================================
# Save model
# ============================================================

def save_model(model):
    """Persist the Spark/SynapseML PipelineModel."""

    Path(MODEL_PATH).parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    model.write().overwrite().save(MODEL_PATH)

    print(f"SynapseML model saved: {MODEL_PATH}")


# ============================================================
# Save anomaly results
# ============================================================

def save_results(df: DataFrame):
    """Persist results as Spark Parquet."""

    Path(OUTPUT_PATH).parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    # Remove internal ML columns from the final result.
    result = df.drop(
        "features",
        "predictedLabel",
        "outlierScore",
    )

    result.write.mode("overwrite").parquet(OUTPUT_PATH)

    print(f"Anomaly results saved to: {OUTPUT_PATH}")

    return result


# ============================================================
# Main
# ============================================================

def main():

    print("=" * 70)
    print("LogHawk Stage B - SynapseML Isolation Forest")
    print("=" * 70)

    spark = create_spark_session()

    try:
        # --------------------------------------------------------
        # 1. Load Stage A dataset
        # --------------------------------------------------------

        df = load_features(spark)

        # --------------------------------------------------------
        # 2. Clean features
        # --------------------------------------------------------

        df = clean_features(df)

        # --------------------------------------------------------
        # 3. Select NORMAL baseline
        # --------------------------------------------------------

        baseline = select_normal_baseline(df)

        # --------------------------------------------------------
        # 4. Train SynapseML model
        # --------------------------------------------------------

        model = train_model(baseline)

        # --------------------------------------------------------
        # 5. Score every feature window
        # --------------------------------------------------------

        df = calculate_scores(df, model)

        # --------------------------------------------------------
        # 6. Calculate severity
        # --------------------------------------------------------

        df = calculate_severity(df)

        # --------------------------------------------------------
        # 7. Generate explanation
        # --------------------------------------------------------

        df = generate_reason(df)

        # --------------------------------------------------------
        # 8. Save Spark/SynapseML model
        # --------------------------------------------------------

        save_model(model)

        # --------------------------------------------------------
        # 9. Save anomaly results
        # --------------------------------------------------------

        result = save_results(df)

        # --------------------------------------------------------
        # 10. Print summary
        # --------------------------------------------------------

        print()
        print("=" * 70)
        print("ANOMALY SUMMARY")
        print("=" * 70)

        result.groupBy("severity") \
            .count() \
            .orderBy(F.desc("count")) \
            .show(truncate=False)

        anomaly_count = result.filter(
            F.col("is_anomaly")
        ).count()

        print(f"Detected anomalies: {anomaly_count}")

        print()
        print("Top anomalies:")

        columns = [
            "timestamp",
            "service",
            "anomaly_score",
            "severity",
            "reason",
        ]

        anomaly_results = (
            result
            .filter(F.col("is_anomaly"))
            .orderBy(F.desc("anomaly_score"))
            .select(*columns)
            .limit(20)
        )

        if anomaly_results.limit(1).count() == 0:
            print("No anomalies detected.")
        else:
            anomaly_results.show(
                20,
                truncate=False,
            )

        print()
        print("Stage B completed successfully.")

    finally:
        spark.stop()


if __name__ == "__main__":
    main()
