# anomaly detector interface, cuML support, and scikit-learn compatibility
"""
LogHawk Stage B - Folder-Based Detector Training and Ensemble Detection

Consumes the per-input-file feature datasets generated by Stage A and writes
a corresponding anomaly dataset for each input file.

Stage A layout:
    s3://loghawk-data/features/2026-09-28/<inputfilename>/

Stage B layout:
    s3://loghawk-data/anomalies/2026-09-28/<inputfilename>/
        anomaly_results.parquet

Optional identity mapping:
    s3://loghawk-data/identitymapping/2026-09-28/
        identitymapping_<inputfilename>.json

The identity mapping is not required for Isolation Forest itself because Stage A
already writes entity_id and identity metadata into the feature dataset.
When a mapping exists, Stage B loads it and validates the recommended entity
column where that column is present in the Stage A output.
"""

from io import BytesIO
import json
import os
import traceback

import fsspec
import joblib
import numpy as np
import pandas as pd

import loghawk.config as config
from loghawk.anomaly_detection.anomaly_detector import (
    AnomalyDetector,
    create_anomaly_detector,
)
from loghawk.anomaly_detection.detector_metadata import (
    DetectorMetadata,
    package_version,
)
from loghawk.anomaly_detection.detector_ensemble import (
    calibration_reference,
    combine_normalized_scores,
    normalize_scores,
)
from loghawk.anomaly_detection.model_registry import ModelRegistry


# ============================================================
# S3 / RustFS / SeaweedFS configuration
# ============================================================

LH_S3_ENDPOINT = config.LH_S3_ENDPOINT
LH_S3_BUCKET = config.LH_S3_BUCKET
LH_S3_ACCESS_KEY_ID = config.LH_S3_ACCESS_KEY_ID
LH_S3_SECRET_ACCESS_KEY = config.LH_S3_SECRET_ACCESS_KEY
LH_S3_REGION = config.LH_S3_REGION


# ============================================================
# Stage B paths
# ============================================================

INPUT_PATH = (
    f"s3://{LH_S3_BUCKET}/features/"
    "2026-09-28/"
)

OUTPUT_PATH = (
    f"s3://{LH_S3_BUCKET}/anomalies/"
    "2026-09-28/"
)

IDENTITY_MAPPING_PATH = (
    f"s3://{LH_S3_BUCKET}/identitymapping/"
    "2026-09-28/"
)

# Model artifacts are kept per input dataset so that each Stage A input
# folder gets its own trained Isolation Forest and scaler.
MODEL_PATH = (
    f"s3://{LH_S3_BUCKET}/models/"
    "2026-09-28/"
)

# ============================================================
# S3 filesystem
# ============================================================


def get_s3_filesystem():
    """
    Create an S3 filesystem for the configured S3-compatible object store.
    """
    return fsspec.filesystem(
        "s3",
        key=LH_S3_ACCESS_KEY_ID,
        secret=LH_S3_SECRET_ACCESS_KEY,
        client_kwargs={
            "endpoint_url": LH_S3_ENDPOINT,
            "region_name": LH_S3_REGION,
        },
        config_kwargs={
            "s3": {
                "addressing_style": "path"
            }
        },
    )


# ============================================================
# Isolation Forest configuration
# ============================================================

BASELINE_RATIO = 0.70
MIN_BASELINE_ROWS = 20

CONTAMINATION = 0.05
N_ESTIMATORS = 200
RANDOM_STATE = 42


# ============================================================
# Columns generated by Stage A
# ============================================================

METADATA_COLUMNS = [
    "timestamp",
    "entity_id",
    "service",
    "application_id",
    "app_name",
    "container_name",
    "pod_name",
    "namespace",
    "hostname",
    "host",
    "database",
    "device",
]

ML_FEATURE_COLUMNS = [
    "total_log_count",
    "info_count",
    "warning_count",
    "error_count",
    "http_4xx_count",
    "http_5xx_count",
    "timeout_count",
    "connection_error_count",
    "authentication_failure_count",
    "unique_exception_count",
    "unique_error_message_count",
    "error_rate",
    "warning_rate",
    "http_5xx_rate",
    "timeout_rate",
]


# ============================================================
# Utility functions
# ============================================================


def normalize_s3_uri(path: str) -> str:
    """Convert Hadoop S3A URI to fsspec-compatible S3 URI."""
    if path.startswith("s3a://"):
        return "s3://" + path[len("s3a://"):]
    return path


def normalize_s3_folder(path: str) -> str:
    """Normalize an S3 folder URI so it has one trailing slash."""
    path = normalize_s3_uri(path)
    return path.rstrip("/") + "/"


def input_folder_name(feature_folder: str) -> str:
    """
    Return the Stage A input-folder name.

    Example:
        s3://bucket/features/2026-09-28/container_logs/
        -> container_logs
    """
    return feature_folder.rstrip("/").split("/")[-1]


def derive_identity_mapping_path(
    input_folder: str,
    identity_mapping_folder: str,
) -> str:
    """
    Derive the identity mapping corresponding to one Stage A input folder.

    Example:
        container_logs/
        ->
        identitymapping_container_logs.json
    """
    name = input_folder_name(input_folder)

    return (
        normalize_s3_folder(identity_mapping_folder)
        + f"identitymapping_{name}.json"
    )


def derive_output_folder(
    input_folder: str,
    output_root: str,
) -> str:
    """
    Derive the Stage B output folder for one Stage A input folder.
    """
    name = input_folder_name(input_folder)
    return normalize_s3_folder(output_root) + name + "/"


def derive_model_path(
    input_folder: str,
    model_root: str,
) -> tuple[str, str]:
    """
    Derive per-input model and scaler paths.
    """
    name = input_folder_name(input_folder)

    root = normalize_s3_folder(model_root)

    return (
        root + f"isolation_forest_{name}.joblib",
        root + f"isolation_scaler_{name}.joblib",
    )


def list_feature_folders(input_root: str, fs):
    """
    Enumerate the direct Stage A output folders.

    Expected layout:

        features/<date>/<inputfilename>/
            part-*.parquet
            ...

    Only direct child folders are returned. Internal Parquet files are handled
    by load_features().
    """
    input_root = normalize_s3_folder(input_root)
    prefix = input_root.replace("s3://", "").rstrip("/")

    entries = fs.ls(prefix, detail=True)

    folders = []

    for entry in entries:
        if isinstance(entry, dict):
            name = entry.get("name", "")
            entry_type = entry.get("type", "")
        else:
            name = str(entry)
            entry_type = ""

        if not name:
            continue

        if entry_type == "directory" or name.endswith("/"):
            folder = "s3://" + name.rstrip("/") + "/"
            folder_name = input_folder_name(folder)

            if folder_name.startswith("_") or folder_name.startswith("."):
                continue

            folders.append(folder)

    folders.sort()

    return folders


def validate_features(df: pd.DataFrame):
    """
    Verify that Stage A metadata and ML feature columns exist.

    entity_id is required because Stage A now uses generic entity identity.
    Optional identity metadata is preserved when present.
    """
    required_columns = [
        "timestamp",
        "entity_id",
        *ML_FEATURE_COLUMNS,
    ]

    missing = [
        column
        for column in required_columns
        if column not in df.columns
    ]

    if missing:
        raise ValueError(
            f"Missing required Stage A columns: {missing}"
        )


def load_identity_mapping(
    input_folder: str,
    identity_mapping_folder: str,
    fs,
):
    """
    Load the mapping for one input dataset if it exists.

    The mapping is optional for Stage B because Stage A already writes
    entity_id. If present, it is used for validation/context.
    """
    mapping_path = derive_identity_mapping_path(
        input_folder,
        identity_mapping_folder,
    )

    key = mapping_path.replace("s3://", "")

    if not fs.exists(key):
        print(
            f"Identity mapping not found; continuing without it: "
            f"{mapping_path}"
        )
        return None, mapping_path

    print(f"Reading identity mapping: {mapping_path}")

    with fs.open(key, "rb") as f:
        mapping = json.load(f)

    identity_mapping = mapping.get("identity_mapping", {})

    if not isinstance(identity_mapping, dict):
        raise ValueError(
            f"Invalid identity_mapping section in {mapping_path}"
        )

    return mapping, mapping_path


def validate_identity_mapping_against_features(
    mapping,
    mapping_path: str,
    df: pd.DataFrame,
):
    """
    Validate the optional mapping against Stage A feature output.

    Stage B does not use the mapping to construct entity_id; Stage A has already
    done that. This check prevents an inconsistent mapping from silently being
    accepted.
    """
    if mapping is None:
        return

    identity_mapping = mapping.get("identity_mapping", {})

    recommended_entity_column = identity_mapping.get(
        "recommended_entity_column"
    )

    if (
        recommended_entity_column
        and recommended_entity_column not in df.columns
    ):
        print(
            "Warning: identity mapping recommends "
            f"'{recommended_entity_column}', but that column is not present "
            "in the Stage A feature dataset. Stage B will continue using "
            "Stage A's entity_id."
        )


def load_features(input_folder: str, fs):
    """
    Load all Parquet files under one Stage A input folder.

    Example:
        s3://loghawk-data/features/2026-09-28/container_logs/
    """
    input_folder = normalize_s3_folder(input_folder)

    s3_prefix = input_folder.replace("s3://", "").rstrip("/")

    print(f"Reading features from: {input_folder}")

    # Stage A may have written or replaced these objects since this
    # filesystem instance cached the folder listing.
    fs.invalidate_cache(s3_prefix)
    parquet_files = fs.glob(
        f"{s3_prefix}/**/*.parquet"
    )

    if not parquet_files:
        raise FileNotFoundError(
            f"No Parquet files found under: {input_folder}"
        )

    dfs = []

    for file_path in parquet_files:
        print(f"Reading: {file_path}")

        with fs.open(file_path, "rb") as f:
            df = pd.read_parquet(f)

        dfs.append(df)

    if not dfs:
        raise ValueError(
            f"No feature data loaded from {input_folder}"
        )

    df = pd.concat(dfs, ignore_index=True)

    validate_features(df)

    return df


def clean_features(df):
    """
    Clean numeric Stage A features while preserving metadata.
    """
    df = df.copy()

    df["timestamp"] = pd.to_datetime(
        df["timestamp"],
        errors="coerce",
    )

    df["entity_id"] = (
        df["entity_id"]
        .fillna("unknown-entity")
        .astype(str)
    )

    for column in ML_FEATURE_COLUMNS:
        df[column] = pd.to_numeric(
            df[column],
            errors="coerce",
        )

    df[ML_FEATURE_COLUMNS] = (
        df[ML_FEATURE_COLUMNS]
        .replace([np.inf, -np.inf], np.nan)
        .fillna(0)
    )

    return df


# ============================================================
# Baseline selection
# ============================================================


def select_normal_baseline(df):
    """
    Select the earliest portion of the dataset as the normal baseline.

    Stage A uses timestamp as the one-minute aggregation timestamp.
    """
    if "timestamp" not in df.columns:
        raise ValueError(
            "Stage A feature dataset must contain a 'timestamp' column."
        )

    df = df.sort_values("timestamp").reset_index(drop=True)

    baseline_size = max(
        int(len(df) * BASELINE_RATIO),
        MIN_BASELINE_ROWS,
    )

    baseline_size = min(
        baseline_size,
        len(df),
    )

    baseline = df.iloc[:baseline_size].copy()

    print(
        f"Selected {len(baseline)} rows as normal baseline"
    )

    return baseline


# ============================================================
# Train Isolation Forest
# ============================================================


def train_model(baseline, algorithm_id: str | None = None):
    if algorithm_id is None:
        selected = config.LH_EFFECTIVE_ANOMALY_ALGORITHMS
        if len(selected) != 1:
            raise ValueError(
                "The standalone one-shot Stage B entry point supports one "
                "algorithm; use Temporal Train/Detect for ensembles."
            )
        algorithm_id = selected[0]
    X_train = baseline[ML_FEATURE_COLUMNS].values
    detector = create_anomaly_detector(algorithm=algorithm_id)
    print(f"Training detector: {detector.algorithm} (backend: {detector.backend})...")
    print(
        f"Detector: algorithm={detector.algorithm}, backend={detector.backend}, "
        f"capabilities={detector.capabilities.to_dict()}"
    )
    detector.train(X_train)

    print(
        f"Detector training completed: {detector.algorithm} "
        f"(backend: {detector.backend})"
    )

    return detector, None


# ============================================================
# Calculate anomaly score
# ============================================================


def calculate_scores(df, model, scaler):
    X = df[ML_FEATURE_COLUMNS].values
    if isinstance(model, AnomalyDetector):
        anomaly_score, is_anomaly = model.detect(X)
    else:
        # Compatibility for callers still passing the original sklearn pair.
        X_scaled = scaler.transform(X)
        anomaly_score = -model.score_samples(X_scaled)
        is_anomaly = model.predict(X_scaled) == -1
    df["anomaly_score"] = anomaly_score
    df["is_anomaly"] = is_anomaly

    return df


# ============================================================
# Convert anomaly score into severity
# ============================================================


def calculate_severity(df):
    """
    Convert Isolation Forest anomaly results into operational severity.

    NORMAL is assigned to every record classified as normal.

    WARNING / HIGH / CRITICAL are assigned only to records
    classified as anomalous.
    """
    df = df.copy()

    df["severity"] = "NORMAL"

    anomaly_mask = df["is_anomaly"]

    if not anomaly_mask.any():
        return df

    anomaly_scores = df.loc[
        anomaly_mask,
        "anomaly_score",
    ]

    q50 = anomaly_scores.quantile(0.50)
    q90 = anomaly_scores.quantile(0.90)
    q99 = anomaly_scores.quantile(0.99)

    anomaly_conditions = [
        anomaly_scores >= q99,
        anomaly_scores >= q90,
        anomaly_scores >= q50,
    ]

    anomaly_choices = [
        "CRITICAL",
        "HIGH",
        "WARNING",
    ]

    df.loc[anomaly_mask, "severity"] = np.select(
        anomaly_conditions,
        anomaly_choices,
        default="WARNING",
    )

    return df


# ============================================================
# Add human-readable explanation
# ============================================================


def generate_reason(row):
    reasons = []

    if row["error_rate"] > 0:
        reasons.append(
            f"error_rate={row['error_rate']:.2f}"
        )

    if row["http_5xx_count"] > 0:
        reasons.append(
            f"http_5xx={int(row['http_5xx_count'])}"
        )

    if row["timeout_count"] > 0:
        reasons.append(
            f"timeouts={int(row['timeout_count'])}"
        )

    if row["connection_error_count"] > 0:
        reasons.append(
            f"connection_errors="
            f"{int(row['connection_error_count'])}"
        )

    if row["authentication_failure_count"] > 0:
        reasons.append(
            f"auth_failures="
            f"{int(row['authentication_failure_count'])}"
        )

    if row["unique_exception_count"] > 0:
        reasons.append(
            f"unique_exceptions="
            f"{int(row['unique_exception_count'])}"
        )

    if not reasons:
        return "No significant anomaly indicators"

    return "; ".join(reasons)


# ============================================================
# Save model artifacts to S3
# ============================================================


def save_model(
    model,
    scaler,
    model_path: str,
    scaler_path: str,
):
    if not isinstance(model, AnomalyDetector):
        raise TypeError("Stage B v7 saves AnomalyDetector instances.")
    fs = get_s3_filesystem()

    print(f"Saving {model.backend} detector artifact to: {model_path}")

    with fs.open(
        model_path.replace("s3://", ""),
        "wb",
    ) as f:
        model.save(f)

    print("Detector model artifact saved to S3")


# ============================================================
# Save anomaly results to S3
# ============================================================


def save_results(df, output_path: str):
    """
    Save anomaly results for one input dataset.

    output_path points to the complete Parquet file:
        .../<inputfilename>/anomaly_results.parquet
    """
    output_path = normalize_s3_uri(output_path)

    print(f"Saving anomaly results to: {output_path}")

    storage_options = {
        "key": LH_S3_ACCESS_KEY_ID,
        "secret": LH_S3_SECRET_ACCESS_KEY,
        "client_kwargs": {
            "endpoint_url": LH_S3_ENDPOINT,
            "region_name": LH_S3_REGION,
        },
        "config_kwargs": {
            "s3": {
                "addressing_style": "path"
            }
        },
    }

    df.to_parquet(
        output_path,
        index=False,
        storage_options=storage_options,
    )

    print(f"Anomaly results saved to: {output_path}")


# ============================================================
# Process one Stage A input folder
# ============================================================


def process_input_folder(
    input_folder: str,
    output_root: str,
    identity_mapping_folder: str,
    fs,
):
    """
    Process one Stage A feature folder independently.

    Example:

        features/2026-09-28/container_logs/
            ->
        anomalies/2026-09-28/container_logs/
            anomaly_results.parquet
    """
    name = input_folder_name(input_folder)

    print()
    print("=" * 70)
    print(f"STAGE B INPUT: {name}")
    print("=" * 70)

    output_folder = derive_output_folder(
        input_folder,
        output_root,
    )

    output_file = (
        output_folder
        + "anomaly_results.parquet"
    )

    mapping, mapping_path = load_identity_mapping(
        input_folder,
        identity_mapping_folder,
        fs,
    )

    print(f"Feature input : {input_folder}")
    print(f"Identity map  : {mapping_path}")
    print(f"Anomaly output: {output_file}")

    # --------------------------------------------------------
    # 1. Load Stage A dataset
    # --------------------------------------------------------

    df = load_features(
        input_folder,
        fs,
    )

    # --------------------------------------------------------
    # 2. Validate optional identity mapping
    # --------------------------------------------------------

    validate_identity_mapping_against_features(
        mapping,
        mapping_path,
        df,
    )

    # --------------------------------------------------------
    # 3. Clean features
    # --------------------------------------------------------

    df = clean_features(df)

    # --------------------------------------------------------
    # 4. Select NORMAL baseline
    # --------------------------------------------------------

    baseline = select_normal_baseline(df)

    # --------------------------------------------------------
    # 5. Train model
    # --------------------------------------------------------

    model, scaler = train_model(baseline)

    # --------------------------------------------------------
    # 6. Score every feature window
    # --------------------------------------------------------

    df = calculate_scores(
        df,
        model,
        scaler,
    )

    # --------------------------------------------------------
    # 7. Calculate severity
    # --------------------------------------------------------

    df = calculate_severity(df)

    # --------------------------------------------------------
    # 8. Generate explanation
    # --------------------------------------------------------

    df["reason"] = df.apply(
        generate_reason,
        axis=1,
    )

    # --------------------------------------------------------
    # 9. Save model for this input dataset
    # --------------------------------------------------------

    artifact_paths = _group_model_paths(
        MODEL_PATH,
        name,
        model.backend,
        model.algorithm,
    )
    _save_group_artifacts(model, artifact_paths, name)
    _save_model_set(MODEL_PATH, name)

    # --------------------------------------------------------
    # 10. Save anomaly results
    # --------------------------------------------------------

    save_results(
        df,
        output_file,
    )

    # --------------------------------------------------------
    # 11. Print summary
    # --------------------------------------------------------

    anomalies = df[df["is_anomaly"]]

    print()
    print("=" * 70)
    print(f"ANOMALY SUMMARY: {name}")
    print("=" * 70)

    print(df["severity"].value_counts())

    print()
    print(f"Feature windows: {len(df)}")
    print(f"Detected anomalies: {len(anomalies)}")

    if not anomalies.empty:
        print()
        print("Top anomalies:")

        display_columns = [
            "timestamp",
            "entity_id",
            "anomaly_score",
            "severity",
            "reason",
        ]

        display_columns = [
            col
            for col in display_columns
            if col in anomalies.columns
        ]

        print(
            anomalies[display_columns]
            .sort_values("anomaly_score", ascending=False)
            .head(10)
            .to_string(index=False)
        )

    print()
    print(f"Stage B completed for: {name}")

    return output_file


# ============================================================
# Folder-based Stage B run
# ============================================================


def run(input_path: str, output_path: str):
    """
    Execute Stage B for every Stage A feature folder.

    Input:
        s3://loghawk-data/features/2026-09-28/

    Expected children:
        .../container_logs/
        .../loghawk_sample_logs/

    Output:
        s3://loghawk-data/anomalies/2026-09-28/
            container_logs/
                anomaly_results.parquet
            loghawk_sample_logs/
                anomaly_results.parquet
    """
    input_path = normalize_s3_folder(input_path)
    output_path = normalize_s3_folder(output_path)

    identity_mapping_folder = normalize_s3_folder(
        IDENTITY_MAPPING_PATH
    )

    print("=" * 70)
    print("LogHawk Stage B - Folder Processing")
    print("=" * 70)

    print()
    print(f"Input feature folder:")
    print(input_path)

    print()
    print("Identity mapping folder:")
    print(identity_mapping_folder)

    print()
    print("Anomaly output folder:")
    print(output_path)

    fs = get_s3_filesystem()

    feature_folders = list_feature_folders(
        input_path,
        fs,
    )

    print()
    print(f"Feature input folders found: {len(feature_folders)}")

    for index, folder in enumerate(feature_folders, start=1):
        print(f"  {index}. {folder}")

    if not feature_folders:
        raise FileNotFoundError(
            f"No Stage A feature folders found under: {input_path}"
        )

    successful = []
    failed = []

    for index, feature_folder in enumerate(
        feature_folders,
        start=1,
    ):
        print()
        print("#" * 70)
        print(
            f"STAGE B FOLDER {index} OF "
            f"{len(feature_folders)}"
        )
        print("#" * 70)

        try:
            output_file = process_input_folder(
                input_folder=feature_folder,
                output_root=output_path,
                identity_mapping_folder=identity_mapping_folder,
                fs=fs,
            )

            successful.append(
                (
                    feature_folder,
                    output_file,
                )
            )

        except Exception as exc:
            print()
            print(
                f"ERROR processing {feature_folder}:"
            )
            print(f"{type(exc).__name__}: {exc}")
            traceback.print_exc()

            failed.append(
                (
                    feature_folder,
                    str(exc),
                )
            )

    print()
    print("=" * 70)
    print("LogHawk Stage B Folder Run Completed")
    print("=" * 70)

    print(f"Total folders: {len(feature_folders)}")
    print(f"Successful:    {len(successful)}")
    print(f"Failed:        {len(failed)}")

    if successful:
        print()
        print("Successful folders:")

        for input_folder, output_file in successful:
            print(f"  {input_folder}")
            print(f"    -> {output_file}")

    if failed:
        print()
        print("Failed folders:")

        for input_folder, error in failed:
            print(f"  {input_folder}")
            print(f"    {error}")

        raise RuntimeError(
            f"Stage B failed for {len(failed)} "
            f"folder(s)."
        )

    # Return the root output folder because multiple anomaly datasets
    # are now produced.
    return output_path


def _model_registry(model_root: str) -> ModelRegistry:
    return ModelRegistry(normalize_s3_folder(model_root))


def _group_model_paths(
    model_root: str,
    group_name: str,
    backend: str,
    algorithm: str,
) -> dict[str, str]:
    expected_backend, _device = config.anomaly_algorithm_backend_device(algorithm)
    if backend != expected_backend:
        raise ValueError(f"Backend does not match algorithm ID {algorithm!r}")
    return _model_registry(model_root).paths_for_algorithm(group_name, algorithm)


def _s3_key(path: str) -> str:
    return path.replace("s3://", "", 1)


def _save_detector_bundle(
    detector,
    paths: dict[str, str],
    group_name: str,
    calibration_scores: np.ndarray | None,
) -> None:
    fs = get_s3_filesystem()
    for key in ("detector", "scaler", "metadata"):
        fs.makedirs(_s3_key(paths[key]).rsplit("/", 1)[0], exist_ok=True)
    if calibration_scores is not None:
        fs.makedirs(_s3_key(paths["calibration"]).rsplit("/", 1)[0], exist_ok=True)

    print(f"Saving {detector.algorithm} detector to: {paths['detector']}")
    with fs.open(_s3_key(paths["detector"]), "wb") as stream:
        detector.save(stream)

    scaler_buffer = BytesIO()
    np.savez(scaler_buffer, **detector.export_scaler_state())
    with fs.open(_s3_key(paths["scaler"]), "wb") as stream:
        stream.write(scaler_buffer.getvalue())

    calibration_path = None
    if calibration_scores is not None:
        calibration_path = paths["calibration"]
        calibration_buffer = BytesIO()
        np.savez(
            calibration_buffer,
            scores=calibration_reference(calibration_scores),
        )
        with fs.open(_s3_key(calibration_path), "wb") as stream:
            stream.write(calibration_buffer.getvalue())
    elif fs.exists(_s3_key(paths["calibration"])):
        fs.rm(_s3_key(paths["calibration"]))

    versions = {
        "cuml": package_version("cuml"),
        "nvforest": package_version("nvforest"),
        "treelite": package_version("treelite"),
        "scikit-learn": package_version("scikit-learn"),
        "pyod": package_version("pyod"),
        "torch": package_version("torch"),
    }
    metadata = DetectorMetadata(
        backend=detector.backend,
        group=group_name,
        feature_columns=list(ML_FEATURE_COLUMNS),
        detector_path=paths["detector"],
        scaler_path=paths["scaler"],
        backend_metadata=detector.export_backend_metadata(),
        versions=versions,
        capabilities=detector.capabilities.to_dict(),
        algorithm=detector.algorithm,
        detector_type=detector.algorithm,
        calibration_path=calibration_path,
    )
    with fs.open(_s3_key(paths["metadata"]), "w") as stream:
        ModelRegistry.write_metadata(stream, metadata)


def _save_group_artifacts(detector, paths: dict[str, str], group_name: str):
    """Compatibility helper for the standalone, single-detector entry point."""
    _save_detector_bundle(detector, paths, group_name, calibration_scores=None)


def _save_model_set(model_root: str, group_name: str) -> None:
    registry = _model_registry(model_root)
    path = registry.model_set_path(group_name)
    key = _s3_key(path)
    fs = get_s3_filesystem()
    fs.makedirs(key.rsplit("/", 1)[0], exist_ok=True)
    algorithms = list(config.LH_EFFECTIVE_ANOMALY_ALGORITHMS)
    manifest = {
        "manifest_version": 1,
        "group": group_name,
        "algorithms": algorithms,
        "aggregation": "mean_percentile" if len(algorithms) > 1 else "single",
        "threshold": config.LH_ENSEMBLE_THRESHOLD if len(algorithms) > 1 else None,
        "feature_columns": list(ML_FEATURE_COLUMNS),
    }
    with fs.open(key, "w") as stream:
        json.dump(manifest, stream, indent=2)
        stream.write("\n")


def _load_saved_models(model_root: str, group_name: str, fs):
    registry = _model_registry(model_root)
    model_set_path = registry.model_set_path(group_name)
    model_set_key = _s3_key(model_set_path)
    if not fs.exists(model_set_key):
        raise FileNotFoundError(
            "Model-set manifest is missing; run the Stage B Train phase. "
            f"Expected: {model_set_path}"
        )
    with fs.open(model_set_key, "r") as stream:
        model_set = json.load(stream)

    expected_algorithms = list(config.LH_EFFECTIVE_ANOMALY_ALGORITHMS)
    if model_set.get("algorithms") != expected_algorithms:
        raise ValueError(
            "Saved model algorithms do not match the configured list. "
            "Run the Stage B Train phase again."
        )
    if model_set.get("group") != group_name:
        raise ValueError("Saved model-set group does not match the requested group.")
    if model_set.get("feature_columns") != ML_FEATURE_COLUMNS:
        raise ValueError("Saved model-set feature schema does not match Stage B.")

    loaded = []
    for algorithm in expected_algorithms:
        paths = registry.paths_for_algorithm(group_name, algorithm)
        metadata_key = _s3_key(paths["metadata"])
        if not fs.exists(metadata_key):
            raise FileNotFoundError(
                f"Missing metadata for {algorithm}; run the Stage B Train phase."
            )
        with fs.open(metadata_key, "r") as stream:
            metadata = ModelRegistry.read_metadata(stream)
        if (
            metadata.group != group_name
            or metadata.algorithm != algorithm
            or metadata.backend
            != config.anomaly_algorithm_backend_device(algorithm)[0]
            or metadata.feature_columns != ML_FEATURE_COLUMNS
        ):
            raise ValueError(f"Invalid or incompatible model metadata for {algorithm}.")

        detector_key = _s3_key(metadata.detector_path)
        scaler_key = _s3_key(metadata.scaler_path)
        if not fs.exists(detector_key) or not fs.exists(scaler_key):
            raise FileNotFoundError(f"Detector bundle is incomplete for {algorithm}.")
        detector = create_anomaly_detector(algorithm=algorithm)
        with fs.open(detector_key, "rb") as stream:
            detector.load(BytesIO(stream.read()))
        with fs.open(scaler_key, "rb") as stream:
            with np.load(BytesIO(stream.read()), allow_pickle=False) as state:
                detector.load_scaler_state(
                    {key: state[key] for key in state.files}
                )
        detector.load_backend_metadata(metadata.backend_metadata)

        calibration = None
        if len(expected_algorithms) > 1:
            if not metadata.calibration_path:
                raise FileNotFoundError(
                    f"Calibration scores are missing for ensemble member {algorithm}."
                )
            calibration_key = _s3_key(metadata.calibration_path)
            if not fs.exists(calibration_key):
                raise FileNotFoundError(
                    f"Calibration artifact is missing for ensemble member {algorithm}."
                )
            with fs.open(calibration_key, "rb") as stream:
                with np.load(BytesIO(stream.read()), allow_pickle=False) as state:
                    calibration = state["scores"].copy()
        loaded.append((algorithm, detector, metadata, calibration))
    return model_set, loaded


def train(feature_root: str, model_root: str) -> str:
    """Fit the configured detector set for every grouped training dataset."""
    feature_root = normalize_s3_folder(feature_root)
    model_root = normalize_s3_folder(model_root)
    print("=" * 70)
    print("LogHawk Stage B - TRAIN PHASE")
    print("=" * 70)
    fs = get_s3_filesystem()
    feature_folders = list_feature_folders(feature_root, fs)
    if not feature_folders:
        raise FileNotFoundError(
            f"No training feature groups found under: {feature_root}"
        )

    for folder in feature_folders:
        group_name = input_folder_name(folder)
        print(f"Training model for group: {group_name}")
        df = clean_features(load_features(folder, fs))
        if df.empty:
            raise ValueError(f"Training feature group is empty: {folder}")
        model_set_path = _s3_key(
            _model_registry(model_root).model_set_path(group_name)
        )
        if fs.exists(model_set_path):
            fs.rm(model_set_path)

        algorithms = list(config.LH_EFFECTIVE_ANOMALY_ALGORITHMS)
        for algorithm in algorithms:
            detector, _scaler = train_model(df, algorithm)
            print(
                f"Selected detector: algorithm={detector.algorithm}, "
                f"backend={detector.backend}, capabilities="
                f"{detector.capabilities.to_dict()}"
            )
            calibration_scores = None
            if len(algorithms) > 1:
                X_train = df[ML_FEATURE_COLUMNS].values
                calibration_scores, _flags = detector.detect(X_train)
            paths = _model_registry(model_root).paths_for_algorithm(
                group_name, algorithm
            )
            _save_detector_bundle(
                detector, paths, group_name, calibration_scores
            )
        _save_model_set(model_root, group_name)
    print()
    print("=" * 70)
    print("LogHawk Stage B - TRAIN PHASE Completed")
    print("=" * 70)
    print(f"Model output: {model_root}")
    return model_root


def detect(
    feature_root: str,
    anomaly_root: str,
    model_root: str,
) -> str:
    """Score grouped detection features using previously trained artifacts."""
    feature_root = normalize_s3_folder(feature_root)
    anomaly_root = normalize_s3_folder(anomaly_root)
    model_root = normalize_s3_folder(model_root)
    print("=" * 70)
    print("LogHawk Stage B - DETECT PHASE")
    print("=" * 70)
    fs = get_s3_filesystem()
    feature_folders = list_feature_folders(feature_root, fs)
    if not feature_folders:
        raise FileNotFoundError(
            f"No detection feature groups found under: {feature_root}"
        )

    failures = []
    for folder in feature_folders:
        group_name = input_folder_name(folder)
        try:
            df = clean_features(load_features(folder, fs))
            model_set, models = _load_saved_models(model_root, group_name, fs)
            if len(models) == 1:
                algorithm, model, metadata, _calibration = models[0]
                df = calculate_scores(df, model, None)
                df["detector_algorithms"] = algorithm
            else:
                raw_scores = {}
                for algorithm, model, _metadata, calibration in models:
                    scores, _flags = model.detect(
                        df[ML_FEATURE_COLUMNS].values
                    )
                    normalized = normalize_scores(scores, calibration)
                    raw_scores[algorithm] = normalized
                    column = "anomaly_score_" + algorithm.replace("-", "_")
                    df[column] = normalized
                combined, _normalized_scores = combine_normalized_scores(raw_scores)
                df["anomaly_score"] = combined
                df["is_anomaly"] = (
                    combined >= float(model_set["threshold"])
                )
                df["detector_algorithms"] = ",".join(
                    model_set["algorithms"]
                )
            burst_error = (
                (df["error_count"] >= 10)
                & (df["error_rate"] >= 0.5)
            )
            burst_http_5xx = (
                (df["http_5xx_count"] >= 10)
                & (df["http_5xx_rate"] >= 0.5)
            )
            df["is_anomaly"] = (
                df["is_anomaly"] | burst_error | burst_http_5xx
            )
            df = calculate_severity(df)
            df["reason"] = df.apply(generate_reason, axis=1)
            output_file = (
                anomaly_root + group_name + "/anomaly_results.parquet"
            )
            output_key_dir = output_file.replace("s3://", "", 1).rsplit("/", 1)[0]
            fs.makedirs(output_key_dir, exist_ok=True)
            save_results(df, output_file)
            print(f"\nANOMALY SUMMARY: {group_name}")
            print(df["severity"].value_counts())
            print(f"Feature windows: {len(df)}")
            print(f"Detected anomalies: {int(df['is_anomaly'].sum())}")
        except Exception as exc:
            failures.append((group_name, str(exc)))
            print(f"ERROR detecting group {group_name}: {type(exc).__name__}: {exc}")

    if failures:
        raise RuntimeError(f"Stage B detection failed for groups: {failures}")
    print()
    print("=" * 70)
    print("LogHawk Stage B - DETECT PHASE Completed")
    print("=" * 70)
    print(f"Anomaly output: {anomaly_root}")
    return anomaly_root


# ============================================================
# Standalone execution
# ============================================================

if __name__ == "__main__":
    run(
        input_path=INPUT_PATH,
        output_path=OUTPUT_PATH,
    )
