"""
LogHawk Stage B - Isolation Forest Anomaly Detection

Consumes the feature dataset generated by Stage A from S3-compatible
object storage (SeaweedFS) and writes anomaly results back to S3.

Input:
    s3://loghawk-data/features/year=2026/month=09/day=23/

Output:
    s3://loghawk-data/anomalies/year=2026/month=09/day=23/isolation_forest_results.parquet

Model:
    s3://loghawk-data/models/isolation_forest.joblib
    s3://loghawk-data/models/isolation_scaler.joblib
"""

from io import BytesIO

import fsspec
import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler


# ============================================================
# S3 / SeaweedFS configuration
# ============================================================

S3_ENDPOINT = "http://localhost:9000"
S3_BUCKET = "loghawk-data"
S3_ACCESS_KEY = "rustfsadmin"
S3_SECRET_KEY = "rustfsadmin"
S3_REGION = "us-east-1"



# Stage A output
INPUT_PATH = (
    f"s3://{S3_BUCKET}/features/"
    "year=2026/month=09/day=23/"
)

# Stage B output
OUTPUT_PATH = (
    f"s3://{S3_BUCKET}/anomalies/"
    "year=2026/month=09/day=23/"
    "isolation_forest_results.parquet"
)

# Model artifacts
MODEL_PATH = f"s3://{S3_BUCKET}/models/isolation_forest.joblib"
SCALER_PATH = f"s3://{S3_BUCKET}/models/isolation_scaler.joblib"


# ============================================================
# S3 filesystem
# ============================================================

def get_s3_filesystem():
    """
    Create an anonymous S3 filesystem for local SeaweedFS.

    SeaweedFS is running without AWS authentication, so do NOT use
    boto3's DefaultAWSCredentialsProviderChain here.
    """
    return fsspec.filesystem(
        "s3",
        key=S3_ACCESS_KEY,
        secret=S3_SECRET_KEY,
        client_kwargs={
            "endpoint_url": S3_ENDPOINT,
            "region_name": S3_REGION,
        },
        config_kwargs={
            "s3": {
                "addressing_style": "path"
            }
        },
    )    

# ============================================================
# Isolation Forest configuration
# ============================================================

BASELINE_RATIO = 0.70
MIN_BASELINE_ROWS = 20

CONTAMINATION = 0.05
N_ESTIMATORS = 200
RANDOM_STATE = 42


# ============================================================
# Feature columns generated by Stage A
# ============================================================

FEATURE_COLUMNS = [
    "total_log_count",
    "info_count",
    "warning_count",
    "error_count",
    "http_4xx_count",
    "http_5xx_count",
    "timeout_count",
    "connection_error_count",
    "authentication_failure_count",
    "unique_exception_count",
    "unique_error_message_count",
    "error_rate",
    "warning_rate",
    "http_5xx_rate",
    "timeout_rate",
]


# ============================================================
# Utility functions
# ============================================================

def normalize_s3_uri(path: str) -> str:
    """Convert Hadoop S3A URI to fsspec-compatible S3 URI."""
    if path.startswith("s3a://"):
        return "s3://" + path[len("s3a://"):]
    return path

def validate_features(df: pd.DataFrame):
    """Verify that all Stage A feature columns exist."""

    missing = [
        column
        for column in FEATURE_COLUMNS
        if column not in df.columns
    ]

    if missing:
        raise ValueError(
            f"Missing required feature columns: {missing}"
        )

def load_features(input_path: str):
    input_path = normalize_s3_uri(input_path)

    fs = get_s3_filesystem()

    s3_prefix = input_path.replace("s3://", "").rstrip("/")

    print(f"Reading features from: {input_path}")

    parquet_files = fs.glob(f"{s3_prefix}/**/*.parquet")

    if not parquet_files:
        raise FileNotFoundError(
            f"No Parquet files found under: {input_path}"
        )

    dfs = []

    for file_path in parquet_files:
        print(f"Reading: {file_path}")

        with fs.open(file_path, "rb") as f:
            df = pd.read_parquet(f)

        dfs.append(df)

    if not dfs:
        raise ValueError(f"No feature data loaded from {input_path}")

    df = pd.concat(dfs, ignore_index=True)

    validate_features(df)

    return df

def clean_features(df):
    """Clean numerical feature data before ML processing."""

    df = df.copy()

    # Preserve metadata columns such as:
    # timestamp, service

    for column in FEATURE_COLUMNS:
        df[column] = pd.to_numeric(
            df[column],
            errors="coerce",
        )

    df[FEATURE_COLUMNS] = df[FEATURE_COLUMNS].replace(
        [np.inf, -np.inf],
        np.nan,
    )

    df[FEATURE_COLUMNS] = df[FEATURE_COLUMNS].fillna(0)

    return df


# ============================================================
# Baseline selection
# ============================================================

def select_normal_baseline(df):
    """
    Select the earliest portion of the dataset as the normal baseline.

    Stage A uses 'timestamp' as the 1-minute aggregation timestamp.
    """

    if "timestamp" not in df.columns:
        raise ValueError(
            "Stage A feature dataset must contain a 'timestamp' column."
        )

    df = df.sort_values("timestamp").reset_index(drop=True)

    baseline_size = max(
        int(len(df) * BASELINE_RATIO),
        MIN_BASELINE_ROWS
    )

    # Never use more rows than actually exist
    baseline_size = min(baseline_size, len(df))

    baseline = df.iloc[:baseline_size].copy()

    print(f"Selected {len(baseline)} rows as normal baseline")

    return baseline


# ============================================================
# Train Isolation Forest
# ============================================================

def train_model(baseline):

    print("Training Isolation Forest...")

    X_train = baseline[FEATURE_COLUMNS].values

    scaler = StandardScaler()

    X_train_scaled = scaler.fit_transform(X_train)

    model = IsolationForest(
        n_estimators=N_ESTIMATORS,
        contamination=CONTAMINATION,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )

    model.fit(X_train_scaled)

    print("Isolation Forest training completed")

    return model, scaler


# ============================================================
# Calculate anomaly score
# ============================================================

def calculate_scores(df, model, scaler):

    X = df[FEATURE_COLUMNS].values

    X_scaled = scaler.transform(X)

    # score_samples():
    #   Higher = more normal
    #   Lower  = more anomalous
    #
    # Invert it so:
    #   higher anomaly_score = more anomalous

    raw_scores = model.score_samples(X_scaled)

    anomaly_score = -raw_scores

    df["anomaly_score"] = anomaly_score

    # sklearn:
    #   1  = normal
    #  -1  = anomaly

    predictions = model.predict(X_scaled)

    df["is_anomaly"] = predictions == -1

    return df


# ============================================================
# Convert anomaly score into severity
# ============================================================

def calculate_severity(df):

    """
    Convert Isolation Forest anomaly results into operational severity.

    NORMAL is assigned to every record classified as normal.

    WARNING / HIGH / CRITICAL are assigned only to records
    classified as anomalous.
    """

    df = df.copy()
    df["severity"] = "NORMAL"

    anomaly_mask = df["is_anomaly"]

    if not anomaly_mask.any():
        return df

    anomaly_scores = df.loc[
        anomaly_mask,
        "anomaly_score"
    ]

    q50 = anomaly_scores.quantile(0.50)
    q90 = anomaly_scores.quantile(0.90)
    q99 = anomaly_scores.quantile(0.99)

    anomaly_conditions = [
        anomaly_scores >= q99,
        anomaly_scores >= q90,
        anomaly_scores >= q50,
    ]

    anomaly_choices = [
        "CRITICAL",
        "HIGH",
        "WARNING",
    ]

    df.loc[anomaly_mask, "severity"] = np.select(
        anomaly_conditions,
        anomaly_choices,
        default="WARNING",
    )

    return df


# ============================================================
# Add human-readable explanation
# ============================================================

def generate_reason(row):

    reasons = []

    if row["error_rate"] > 0:
        reasons.append(
            f"error_rate={row['error_rate']:.2f}"
        )

    if row["http_5xx_count"] > 0:
        reasons.append(
            f"http_5xx={int(row['http_5xx_count'])}"
        )

    if row["timeout_count"] > 0:
        reasons.append(
            f"timeouts={int(row['timeout_count'])}"
        )

    if row["connection_error_count"] > 0:
        reasons.append(
            f"connection_errors="
            f"{int(row['connection_error_count'])}"
        )

    if row["authentication_failure_count"] > 0:
        reasons.append(
            f"auth_failures="
            f"{int(row['authentication_failure_count'])}"
        )

    if row["unique_exception_count"] > 0:
        reasons.append(
            f"unique_exceptions="
            f"{int(row['unique_exception_count'])}"
        )

    if not reasons:
        return "No significant anomaly indicators"

    return "; ".join(reasons)


# ============================================================
# Save model artifacts to S3
# ============================================================

def save_model(model, scaler):

    fs = get_s3_filesystem()

    print(f"Saving model to: {MODEL_PATH}")

    with fs.open(
        MODEL_PATH.replace("s3://", ""),
        "wb"
    ) as f:
        joblib.dump(model, f)

    print(f"Saving scaler to: {SCALER_PATH}")

    with fs.open(
        SCALER_PATH.replace("s3://", ""),
        "wb"
    ) as f:
        joblib.dump(scaler, f)

    print("Model and scaler saved to S3")


# ============================================================
# Save anomaly results to S3
# ============================================================

def save_results(df):

    print(f"Saving anomaly results to: {OUTPUT_PATH}")

    storage_options = {
        "key": S3_ACCESS_KEY,
        "secret": S3_SECRET_KEY,
        "client_kwargs": {
            "endpoint_url": S3_ENDPOINT,
            "region_name": S3_REGION,
        },
        "config_kwargs": {
            "s3": {
                "addressing_style": "path"
            }
        },
    }

    df.to_parquet(
        OUTPUT_PATH,
        index=False,
        storage_options=storage_options,
    )

    print(
        f"Anomaly results saved to: {OUTPUT_PATH}"
    )


# ============================================================
# Main
# ============================================================
def run(input_path: str, output_path: str):
    """
    Execute Stage B Isolation Forest.
    """

    print("=" * 70)
    print("LogHawk Stage B - Isolation Forest")
    print("=" * 70)

    # --------------------------------------------------------
    # 1. Load Stage A dataset from S3
    # --------------------------------------------------------

    df = load_features(input_path)

    # --------------------------------------------------------
    # 2. Clean features
    # --------------------------------------------------------

    df = clean_features(df)

    # --------------------------------------------------------
    # 3. Select NORMAL baseline
    # --------------------------------------------------------

    baseline = select_normal_baseline(df)

    # --------------------------------------------------------
    # 4. Train model
    # --------------------------------------------------------

    model, scaler = train_model(baseline)

    # --------------------------------------------------------
    # 5. Score every feature window
    # --------------------------------------------------------

    df = calculate_scores(
        df,
        model,
        scaler
    )

    # --------------------------------------------------------
    # 6. Calculate severity
    # --------------------------------------------------------

    df = calculate_severity(df)

    # --------------------------------------------------------
    # 7. Generate explanation
    # --------------------------------------------------------

    df["reason"] = df.apply(
        generate_reason,
        axis=1
    )

    # --------------------------------------------------------
    # 8. Save model
    # --------------------------------------------------------

    save_model(
        model,
        scaler
    )

    # --------------------------------------------------------
    # 9. Save anomaly results
    # --------------------------------------------------------

    save_results(df)

    # --------------------------------------------------------
    # 10. Print summary
    # --------------------------------------------------------

    anomalies = df[df["is_anomaly"]]

    print()
    print("=" * 70)
    print("ANOMALY SUMMARY")
    print("=" * 70)

    print(df["severity"].value_counts())

    print()
    print(f"Detected anomalies: {len(anomalies)}")

    if not anomalies.empty:
        print()
        print("Top anomalies:")

        display_columns = [
            "timestamp",
            "service",
            "anomaly_score",
            "severity",
            "reason",
        ]

        # Only display columns that actually exist.
        display_columns = [
            col for col in display_columns
            if col in anomalies.columns
        ]

        print(
            anomalies[display_columns]
            .sort_values("anomaly_score")
            .head(10)
            .to_string(index=False)
        )
    print()
    print("Stage B completed successfully.")
    return output_path

"""
    print()
    print("=" * 70)
    print("ANOMALY SUMMARY")
    print("=" * 70)

    print(
        df["severity"]
        .value_counts()
        .to_string()
    )

    print()
    print(
        "Detected anomalies:",
        int(df["is_anomaly"].sum())
    )

    print()
    print("Top anomalies:")

    columns = [
        "timestamp",
        "service",
        "anomaly_score",
        "severity",
        "reason",
    ]

    anomaly_results = (
        df[df["is_anomaly"]]
        .sort_values(
            "anomaly_score",
            ascending=False
        )[columns]
        .head(20)
    )

    if anomaly_results.empty:
        print("No anomalies detected.")
    else:
        print(
            anomaly_results.to_string(
                index=False
            )
        )
"""

if __name__ == "__main__":
    run(
        input_path=INPUT_PATH,
        output_path=OUTPUT_PATH,
    )



