# read all files in a folder and generate features for each file using PySpark.
"""
LogHawk - Generic PySpark Feature Engineering

Purpose:
    Read raw logs from S3/S3-compatible storage, load the
    corresponding LLM-generated identity mapping, dynamically
    construct the PySpark schema, derive entity_id, and perform
    deterministic feature engineering.

Example:

    Raw input:
        s3a://loghawk-data/raw/year=2026/month=09/day=23/sample_logs.json

    Identity mapping:
        s3a://loghawk-data/identitymapping/year=2026/month=09/day=23/
        identitymapping_sample_logs.json

    Feature output:
        s3a://loghawk-data/features/year=2026/month=09/day=23/

The identity mapping is generated by Ollama/Llama and contains
the priority order for identifying the entity that generated
each log event.
"""

from pathlib import Path
import json
import os
import re
from typing import Any

import s3fs

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    IntegerType,
    DoubleType,
)

import loghawk.config as config


# ============================================================
# Environment
# ============================================================

os.environ["JAVA_HOME"] = config.JAVA_HOME
os.environ["HADOOP_HOME"] = config.HADOOP_HOME

os.environ["PATH"] = (
    str(Path(config.JAVA_HOME) / "bin")
    + ";"
    + str(Path(config.HADOOP_HOME) / "bin")
    + ";"
    + os.environ.get("PATH", "")
)

os.environ["SPARK_LOCAL_HOSTNAME"] = "localhost"


# ============================================================
# Default paths
# ============================================================

INPUT_PATH = (
    "s3://loghawk-data/raw/2026-09-28/"
)

OUTPUT_PATH = (
    "s3://loghawk-data/features/2026-09-28/"
)


# ============================================================
# Identity mapping configuration
# ============================================================

FALLBACK_ENTITY_ID = "unknown-entity"


# ============================================================
# S3 helper
# ============================================================

def to_spark_s3_path(path: str) -> str:
    if path.startswith("s3://"):
        return "s3a://" + path[len("s3://"):]
    return path

def create_s3_filesystem() -> s3fs.S3FileSystem:
    """
    Create an S3/S3-compatible filesystem for reading the
    identity mapping JSON.

    The same credentials/endpoint used by Spark are taken from
    LogHawk configuration.
    """

    return s3fs.S3FileSystem(
        key=config.LH_S3_ACCESS_KEY_ID,
        secret=config.LH_S3_SECRET_ACCESS_KEY,
        client_kwargs={
            "endpoint_url": config.LH_S3_ENDPOINT,
        },
    )


# ============================================================
# Convert s3a:// -> s3://
# ============================================================

def s3a_to_s3(path: str) -> str:
    """
    s3fs expects s3:// while Spark uses s3a://.
    """

    if path.startswith("s3a://"):
        return "s3://" + path[len("s3a://"):]

    if path.startswith("s3://"):
        return path

    raise ValueError(
        f"Unsupported S3 path: {path}. "
        "Expected s3a:// or s3://."
    )


# ============================================================
# Derive identity mapping path
# ============================================================

def normalize_s3_folder(path: str) -> str:
    """Ensure an S3 folder path ends with '/'."""
    if not (path.startswith("s3://") or path.startswith("s3a://")):
        raise ValueError(
            f"Unsupported S3 path: {path}. "
            "Expected s3:// or s3a://."
        )

    return path if path.endswith("/") else path + "/"


def derive_identity_mapping_folder(
    raw_input_folder: str,
) -> str:
    """
    Convert:

        s3://loghawk-data/raw/2026-09-28/

    to:

        s3://loghawk-data/identitymapping/2026-09-28/
    """
    raw_input_folder = normalize_s3_folder(raw_input_folder)

    scheme = (
        "s3a://"
        if raw_input_folder.startswith("s3a://")
        else "s3://"
    )

    path_without_scheme = re.sub(
        r"^s3a?://",
        "",
        raw_input_folder,
    )

    parts = path_without_scheme.split("/", 1)

    if len(parts) != 2:
        raise ValueError(
            f"Invalid S3 path: {raw_input_folder}"
        )

    bucket = parts[0]
    key = parts[1]

    key_parts = [p for p in key.split("/") if p]

    if "raw" not in key_parts:
        raise ValueError(
            "Raw input folder must contain '/raw/':\n"
            f"{raw_input_folder}"
        )

    raw_index = key_parts.index("raw")
    partition_parts = key_parts[raw_index + 1:]

    if not partition_parts:
        raise ValueError(
            f"No partition path found after /raw/: "
            f"{raw_input_folder}"
        )

    output_key = "/".join(
        ["identitymapping", *partition_parts]
    ) + "/"

    return f"{scheme}{bucket}/{output_key}"


def derive_identity_mapping_path(
    raw_input_path: str,
    identity_mapping_folder: str | None = None,
) -> str:
    """
    Derive the identity mapping file for one raw input file.

    Example:

        Raw:
            s3://loghawk-data/raw/2026-09-28/container_logs.json

        Mapping:
            s3://loghawk-data/identitymapping/2026-09-28/
            identitymapping_container_logs.json
    """
    raw_input_path = raw_input_path.rstrip("/")

    if not (
        raw_input_path.startswith("s3://")
        or raw_input_path.startswith("s3a://")
    ):
        raise ValueError(
            "Raw input path must start with s3:// or s3a://"
        )

    if raw_input_path.endswith("/"):
        raise ValueError(
            "derive_identity_mapping_path() expects a file path, "
            "not a directory."
        )

    if identity_mapping_folder is None:
        # Derive mapping folder from the raw file path.
        path_without_scheme = re.sub(
            r"^s3a?://",
            "",
            raw_input_path,
        )
        parts = path_without_scheme.split("/", 1)

        if len(parts) != 2:
            raise ValueError(
                f"Invalid S3 path: {raw_input_path}"
            )

        bucket = parts[0]
        key = parts[1]
        key_parts = [p for p in key.split("/") if p]

        if "raw" not in key_parts:
            raise ValueError(
                "Raw input path must contain '/raw/':\n"
                f"{raw_input_path}"
            )

        raw_index = key_parts.index("raw")
        partition_parts = key_parts[raw_index + 1:-1]

        scheme = (
            "s3a://"
            if raw_input_path.startswith("s3a://")
            else "s3://"
        )

        identity_mapping_folder = (
            f"{scheme}{bucket}/"
            + "/".join(
                ["identitymapping", *partition_parts]
            )
            + "/"
        )

    identity_mapping_folder = normalize_s3_folder(
        identity_mapping_folder
    )

    input_filename = raw_input_path.split("/")[-1]

    base_filename = input_filename

    if base_filename.endswith(".gz"):
        base_filename = base_filename[:-3]
    elif base_filename.endswith(".gzip"):
        base_filename = base_filename[:-5]

    base_filename = os.path.splitext(base_filename)[0]

    output_filename = (
        f"identitymapping_{base_filename}.json"
    )

    return identity_mapping_folder + output_filename


def list_raw_files(
    raw_input_folder: str,
    fs: s3fs.S3FileSystem,
) -> list[str]:
    """
    Enumerate supported raw log files directly under the input folder.
    """
    raw_input_folder = normalize_s3_folder(raw_input_folder)

    filesystem_path = s3a_to_s3(raw_input_folder)

    entries = fs.ls(
        filesystem_path,
        detail=True,
    )

    raw_files = []

    supported_extensions = (
        ".json",
        ".json.gz",
        ".jsonl",
        ".jsonl.gz",
        ".log",
        ".log.gz",
    )

    for entry in entries:
        if isinstance(entry, dict):
            entry_name = entry["name"]
            if entry.get("type") == "directory":
                continue
        else:
            entry_name = entry

        filename = entry_name.rstrip("/").split("/")[-1]

        if not filename:
            continue

        if filename.startswith("_") or filename.startswith("."):
            continue

        if not filename.lower().endswith(supported_extensions):
            print(
                f"Skipping unsupported file: {filename}"
            )
            continue

        raw_files.append(
            "s3://" + entry_name
            if not entry_name.startswith("s3://")
            else entry_name
        )

    raw_files.sort()
    return raw_files


# ============================================================
# Read identity mapping JSON
# ============================================================

def load_identity_mapping(
    mapping_path: str,
) -> dict[str, Any]:
    """
    Read the complete identity and field mapping JSON from S3.
    """

    filesystem_path = s3a_to_s3(mapping_path)

    print()
    print("=" * 70)
    print("Reading identity mapping")
    print("=" * 70)

    print("Mapping:", mapping_path)

    fs = create_s3_filesystem()

    if not fs.exists(filesystem_path):
        raise FileNotFoundError(
            "Identity mapping JSON was not found:\n"
            f"{mapping_path}\n\n"
            "Run the Ollama identity-mapping step first."
        )

    with fs.open(
        filesystem_path,
        "r",
        encoding="utf-8",
    ) as f:

        mapping_document = json.load(f)

    # --------------------------------------------------------
    # The Ollama program writes:
    #
    # {
    #   "source": {...},
    #   "identity_mapping": {...},
    #   "field_mapping": {...}
    # }
    # --------------------------------------------------------

    if "identity_mapping" not in mapping_document:
        raise ValueError(
            "Invalid identity mapping JSON.\n"
            "Expected 'identity_mapping' section.\n"
            f"Path: {mapping_path}"
        )

    mapping = mapping_document["identity_mapping"]

    if not isinstance(mapping, dict):
        raise ValueError(
            "'identity_mapping' must be a JSON object."
        )

    return mapping_document


# ============================================================
# Validate identity mapping
# ============================================================

def validate_identity_mapping(
    mapping: dict[str, Any],
    available_columns: list[str],
) -> list[str]:
    """
    Validate the LLM-generated identity priority order against
    the actual raw input schema.

    Only columns that really exist in the input are allowed.

    Returns:
        Valid identity columns in priority order.
    """

    available = set(available_columns)

    priority_order = mapping.get(
        "priority_order",
        [],
    )

    if not isinstance(priority_order, list):
        raise ValueError(
            "identity_mapping.priority_order must be a list."
        )

    valid_columns = []

    for column in priority_order:

        if column in available:

            if column not in valid_columns:
                valid_columns.append(column)

        else:

            print(
                f"WARNING: Identity mapping contains column "
                f"'{column}', but it does not exist in the "
                f"raw input schema. Ignoring it."
            )

    # --------------------------------------------------------
    # If the LLM mapping contains identity_columns but omitted
    # something from priority_order, we can consider it as a
    # secondary candidate.
    # --------------------------------------------------------

    identity_columns = mapping.get(
        "identity_columns",
        [],
    )

    if isinstance(identity_columns, list):

        for column in identity_columns:

            if (
                column in available
                and column not in valid_columns
            ):
                valid_columns.append(column)

    return valid_columns


FIELD_ROLE_FALLBACKS = {
    "timestamp_column": "timestamp",
    "level_column": "level",
    "message_column": "message",
    "status_code_column": "status_code",
    "exception_column": "exception",
}


def validate_field_mapping(
    field_mapping: dict[str, Any] | None,
    available_columns: list[str],
) -> dict[str, str | None]:
    """Resolve field roles against the source schema, including legacy names."""
    if not isinstance(field_mapping, dict):
        field_mapping = {}
    available = set(available_columns)
    resolved = {}

    for role, fallback_column in FIELD_ROLE_FALLBACKS.items():
        column = field_mapping.get(role)

        if column is not None and (
            not isinstance(column, str)
            or column not in available
        ):
            print(
                f"WARNING: Field mapping {role}='{column}' is not in "
                "the source schema; checking the legacy field name."
            )
            column = None

        if column is None and fallback_column in available:
            column = fallback_column

        resolved[role] = column

    if resolved["timestamp_column"] is None:
        raise ValueError(
            "No valid timestamp field is mapped. "
            f"Available columns: {sorted(available)}"
        )

    return resolved


# ============================================================
# Construct dynamic Spark schema
# ============================================================

def construct_schema(
    inferred_schema: StructType,
    identity_columns: list[str],
    field_mapping: dict[str, str | None],
) -> StructType:
    """
    Construct a Spark schema dynamically from the actual raw
    input schema.

    Identity columns are forced to StringType because they may
    originate from different source systems and formats.

    Common LogHawk fields receive predictable types where
    appropriate.

    Unknown/source-specific fields are preserved using their
    inferred Spark data types.
    """

    identity_set = set(identity_columns)
    role_types = {
        field_mapping["timestamp_column"]: StringType(),
        field_mapping["level_column"]: StringType(),
        field_mapping["message_column"]: StringType(),
        field_mapping["exception_column"]: StringType(),
        field_mapping["status_code_column"]: IntegerType(),
    }

    fields = []

    for field in inferred_schema.fields:

        field_name = field.name

        # ----------------------------------------------------
        # Identity columns must be strings.
        # ----------------------------------------------------

        if field_name in identity_set:

            fields.append(
                StructField(
                    field_name,
                    StringType(),
                    True,
                )
            )

        elif field_name in role_types and role_types[field_name] is not None:
            fields.append(
                StructField(
                    field_name,
                    role_types[field_name],
                    True,
                )
            )

        # ----------------------------------------------------
        # Unknown source-specific columns retain their
        # inferred types.
        # ----------------------------------------------------

        else:

            fields.append(
                StructField(
                    field_name,
                    field.dataType,
                    field.nullable,
                )
            )

    return StructType(fields)


# ============================================================
# Construct entity_id expression
# ============================================================

def build_entity_id_expression(
    identity_columns: list[str],
):
    """
    Build the deterministic PySpark expression used to create
    entity_id from the LLM-generated priority order.
    """

    expressions = []

    for column in identity_columns:

        expressions.append(
            F.when(
                F.col(column).isNotNull()
                & (F.trim(F.col(column)) != ""),
                F.trim(F.col(column)),
            )
        )

    if not expressions:
        return F.lit(FALLBACK_ENTITY_ID)

    return F.coalesce(
        *expressions,
        F.lit(FALLBACK_ENTITY_ID),
    )


# ============================================================
# Main Stage A
# ============================================================

def _run_single_file(
    spark: SparkSession,
    input_path: str,
    output_path: str,
    identity_mapping_folder: str,
):
    """
    Process exactly one raw file.

    The file gets its own identity mapping and its own Parquet
    dataset under:

        features/<date>/<input_filename>/
    """

    identity_mapping_path = derive_identity_mapping_path(
        input_path,
        identity_mapping_folder,
    )

    mapping_document = load_identity_mapping(
        identity_mapping_path
    )

    print()
    print("=" * 70)
    print("LogHawk Stage A - Processing File")
    print("=" * 70)

    print("Input :", input_path)
    print("Mapping:", identity_mapping_path)
    print("Output:", output_path)

    # ========================================================
    # Read raw JSON and infer actual source schema
    # ========================================================

    print()
    print("Inferring raw log schema from S3...")

    spark_input_path = to_spark_s3_path(input_path)
    spark_output_path = to_spark_s3_path(output_path)

    inferred_logs = (
        spark.read
        .option("samplingRatio", 0.1)
        .json(spark_input_path)
    )

    print()
    print("Inferred schema:")
    inferred_logs.printSchema()

    inferred_schema = inferred_logs.schema
    available_columns = inferred_logs.columns

    print()
    print("Raw columns:")
    print(available_columns)

    # ========================================================
    # Validate LLM identity mapping
    # ========================================================

    identity_columns = validate_identity_mapping(
        mapping=mapping_document["identity_mapping"],
        available_columns=available_columns,
    )

    field_mapping = validate_field_mapping(
        mapping_document.get("field_mapping"),
        available_columns,
    )

    print()
    print("=" * 70)
    print("Validated identity mapping")
    print("=" * 70)

    if identity_columns:
        for index, column in enumerate(
            identity_columns,
            start=1,
        ):
            print(
                f"{index}. {column}"
            )
    else:
        print(
            "No valid identity columns found."
        )
        print(
            f"Using fallback entity_id: "
            f"{FALLBACK_ENTITY_ID}"
        )

    # ========================================================
    # Construct final PySpark schema
    # ========================================================

    schema = construct_schema(
        inferred_schema=inferred_schema,
        identity_columns=identity_columns,
        field_mapping=field_mapping,
    )

    # ========================================================
    # Read raw logs using constructed schema
    # ========================================================

    print()
    print("Reading raw logs using constructed schema...")

    logs = (
        spark.read
        .schema(schema)
        .json(spark_input_path)
    )

    # ========================================================
    # Standardize common fields
    # ========================================================

    timestamp_source = field_mapping["timestamp_column"]
    logs = logs.withColumn(
        "event_time",
        F.to_timestamp(F.col(timestamp_source)),
    )

    level_source = field_mapping["level_column"]
    level_value = (
        F.col(level_source).cast("string")
        if level_source
        else F.lit("UNKNOWN")
    )
    logs = logs.withColumn(
        "level",
        F.upper(F.trim(F.coalesce(level_value, F.lit("UNKNOWN")))),
    )

    message_source = field_mapping["message_column"]
    message_value = (
        F.col(message_source).cast("string")
        if message_source
        else F.lit("")
    )
    logs = logs.withColumn(
        "message",
        F.coalesce(message_value, F.lit("")),
    )

    exception_source = field_mapping["exception_column"]
    exception_value = (
        F.col(exception_source).cast("string")
        if exception_source
        else F.lit("")
    )
    logs = logs.withColumn(
        "exception",
        F.coalesce(exception_value, F.lit("")),
    )

    status_source = field_mapping["status_code_column"]
    status_value = (
        F.col(status_source).cast("int")
        if status_source
        else F.lit(None).cast("int")
    )
    logs = logs.withColumn("status_code", status_value)

    # ========================================================
    # Normalize identity columns
    # ========================================================

    for column in identity_columns:
        logs = logs.withColumn(
            column,
            F.when(
                F.col(column).isNotNull()
                & (
                    F.trim(
                        F.col(column)
                    ) != ""
                ),
                F.trim(
                    F.col(column)
                ),
            ).otherwise(None),
        )

    # ========================================================
    # Construct generic entity_id
    # ========================================================

    entity_id_expression = (
        build_entity_id_expression(
            identity_columns
        )
    )

    logs = logs.withColumn(
        "entity_id",
        entity_id_expression,
    )

    # ========================================================
    # Deterministic feature engineering
    # ========================================================

    logs = (
        logs

        .withColumn(
            "is_info",
            (
                F.col("level") == "INFO"
            ).cast("int"),
        )

        .withColumn(
            "is_warn",
            F.col("level")
            .isin(
                "WARN",
                "WARNING",
            )
            .cast("int"),
        )

        .withColumn(
            "is_error",
            (
                F.col("level") == "ERROR"
            ).cast("int"),
        )

        .withColumn(
            "is_http_4xx",
            (
                (F.col("status_code") >= 400)
                & (F.col("status_code") < 500)
            ).cast("int"),
        )

        .withColumn(
            "is_http_5xx",
            (
                (F.col("status_code") >= 500)
                & (F.col("status_code") < 600)
            ).cast("int"),
        )

        .withColumn(
            "is_timeout",
            F.when(
                F.lower(
                    F.col("message")
                ).contains("timeout"),
                1,
            ).otherwise(0),
        )

        .withColumn(
            "is_connection_error",
            F.when(
                F.lower(
                    F.col("message")
                ).rlike(
                    "connection refused|"
                    "connection reset|"
                    "connection failed"
                ),
                1,
            ).otherwise(0),
        )

        .withColumn(
            "is_auth_failure",
            F.when(
                F.lower(
                    F.col("message")
                ).rlike(
                    "authentication failed|"
                    "unauthorized|"
                    "invalid credentials|"
                    "login failed"
                ),
                1,
            ).otherwise(0),
        )
    )

    # ========================================================
    # Remove records with invalid timestamps
    # ========================================================

    logs = logs.filter(
        F.col("event_time").isNotNull()
    )

    # ========================================================
    # One-minute window
    # ========================================================

    logs = logs.withColumn(
        "window",
        F.window(
            F.col("event_time"),
            "1 minute",
        ),
    )

    # ========================================================
    # Aggregate by generic entity
    # ========================================================

    aggregation_expressions = []

    for column in identity_columns:
        aggregation_expressions.append(
            F.first(
                column,
                ignorenulls=True,
            ).alias(column)
        )

    aggregation_expressions.extend(
        [
            F.count("*").alias(
                "total_log_count"
            ),

            F.sum("is_info").alias(
                "info_count"
            ),

            F.sum("is_warn").alias(
                "warning_count"
            ),

            F.sum("is_error").alias(
                "error_count"
            ),

            F.sum("is_http_4xx").alias(
                "http_4xx_count"
            ),

            F.sum("is_http_5xx").alias(
                "http_5xx_count"
            ),

            F.sum("is_timeout").alias(
                "timeout_count"
            ),

            F.sum(
                "is_connection_error"
            ).alias(
                "connection_error_count"
            ),

            F.sum(
                "is_auth_failure"
            ).alias(
                "authentication_failure_count"
            ),

            F.countDistinct(
                F.when(
                    F.col("exception") != "",
                    F.col("exception"),
                )
            ).alias(
                "unique_exception_count"
            ),

            F.countDistinct(
                F.when(
                    F.col("level") == "ERROR",
                    F.col("message"),
                )
            ).alias(
                "unique_error_message_count"
            ),
        ]
    )

    features = (
        logs
        .groupBy(
            "entity_id",
            "window",
        )
        .agg(
            *aggregation_expressions
        )
    )

    # ========================================================
    # Window timestamp
    # ========================================================

    features = (
        features
        .withColumn(
            "timestamp",
            F.col("window.start"),
        )
        .drop("window")
    )

    # ========================================================
    # Rates
    # ========================================================

    features = (
        features

        .withColumn(
            "error_rate",
            F.when(
                F.col("total_log_count") > 0,
                F.col("error_count")
                / F.col("total_log_count"),
            ).otherwise(0.0),
        )

        .withColumn(
            "warning_rate",
            F.when(
                F.col("total_log_count") > 0,
                F.col("warning_count")
                / F.col("total_log_count"),
            ).otherwise(0.0),
        )

        .withColumn(
            "http_5xx_rate",
            F.when(
                F.col("total_log_count") > 0,
                F.col("http_5xx_count")
                / F.col("total_log_count"),
            ).otherwise(0.0),
        )

        .withColumn(
            "timeout_rate",
            F.when(
                F.col("total_log_count") > 0,
                F.col("timeout_count")
                / F.col("total_log_count"),
            ).otherwise(0.0),
        )
    )

    # ========================================================
    # Build final output columns
    # ========================================================

    metadata_columns = [
        "timestamp",
        "entity_id",
    ]

    for column in identity_columns:
        if column not in metadata_columns:
            metadata_columns.append(column)

    feature_columns = [
        "total_log_count",
        "info_count",
        "warning_count",
        "error_count",
        "error_rate",
        "warning_rate",
        "http_4xx_count",
        "http_5xx_count",
        "http_5xx_rate",
        "timeout_count",
        "timeout_rate",
        "connection_error_count",
        "authentication_failure_count",
        "unique_exception_count",
        "unique_error_message_count",
    ]

    final_columns = (
        metadata_columns
        + feature_columns
    )

    features = features.select(
        *final_columns
    )

    # ========================================================
    # Display results
    # ========================================================

    print()
    print("=" * 70)
    print("Generated feature dataset")
    print("=" * 70)

    features.orderBy(
        F.col("timestamp")
    ).show(
        20,
        truncate=False,
    )

    # ========================================================
    # Write per-file feature dataset
    # ========================================================

    print()
    print(
        "Writing feature data to S3..."
    )

    (
        features
        .write
        .mode("overwrite")
        .parquet(spark_output_path)
    )

    print()
    print("=" * 70)
    print("File feature generation completed")
    print("=" * 70)

    print()
    print("Raw input:")
    print(input_path)

    print()
    print("Identity mapping:")
    print(identity_mapping_path)

    print()
    print("Entity priority:")
    print(identity_columns)

    print()
    print("Feature output:")
    print(output_path)

    return output_path


def run(
    input_path: str,
    output_path: str,
):
    """
    Run LogHawk Stage A over a raw S3 folder.

    Example:

        input_path =
            s3://loghawk-data/raw/2026-09-28/

        output_path =
            s3://loghawk-data/features/2026-09-28/

    For every raw file:

        raw/<file>
             |
             +--> identitymapping/identitymapping_<file>.json
             |
             +--> features/<file>/

    Stage A does not start processing a file until its corresponding
    identity mapping exists.

    The function returns only after all files have been processed.
    """

    input_path = normalize_s3_folder(
        input_path
    )

    output_path = normalize_s3_folder(
        output_path
    )

    identity_mapping_folder = (
        derive_identity_mapping_folder(
            input_path
        )
    )

    fs = create_s3_filesystem()

    raw_files = list_raw_files(
        input_path,
        fs,
    )

    if not raw_files:
        raise RuntimeError(
            "No supported raw log files found in:\n"
            f"{input_path}"
        )

    print()
    print("=" * 70)
    print("LogHawk Stage A - Folder Processing")
    print("=" * 70)

    print()
    print("Input folder:")
    print(input_path)

    print()
    print("Identity mapping folder:")
    print(identity_mapping_folder)

    print()
    print("Feature output folder:")
    print(output_path)

    print()
    print(f"Raw files found: {len(raw_files)}")

    for index, path in enumerate(
        raw_files,
        start=1,
    ):
        print(
            f"  {index}. {path}"
        )

    # ========================================================
    # Create ONE Spark session for the complete Stage A run.
    # ========================================================

    spark = (
        SparkSession.builder
        .appName(
            "LogHawk-FeatureEngineering-S3"
        )
        .master("local[1]")
        .config(
            "spark.jars.packages",
            "org.apache.hadoop:hadoop-aws:3.3.4",
        )
        .config(
            "spark.hadoop.fs.s3a.impl",
            "org.apache.hadoop.fs.s3a.S3AFileSystem",
        )
        .config(
            "spark.hadoop.fs.s3a.endpoint",
            config.LH_S3_ENDPOINT,
        )
        .config(
            "spark.hadoop.fs.s3a.access.key",
            config.LH_S3_ACCESS_KEY_ID,
        )
        .config(
            "spark.hadoop.fs.s3a.secret.key",
            config.LH_S3_SECRET_ACCESS_KEY,
        )
        .config(
            "spark.hadoop.fs.s3a.path.style.access",
            "true",
        )
        .config(
            "spark.hadoop.fs.s3a.connection.ssl.enabled",
            "false",
        )
        .config(
            "spark.hadoop.fs.s3a.aws.credentials.provider",
            "org.apache.hadoop.fs.s3a."
            "SimpleAWSCredentialsProvider",
        )
        .config(
            "spark.hadoop.fs.s3a.connection.timeout",
            "60000",
        )
        .config(
            "spark.hadoop.fs.s3a.connection.establish.timeout",
            "60000",
        )
        .config(
            "spark.hadoop.fs.s3a.threads.keepalivetime",
            "60",
        )
        .config(
            "spark.hadoop.fs.s3a.multipart.purge",
            "false",
        )
        .getOrCreate()
    )

    spark.sparkContext.setLogLevel("WARN")

    successful = []
    failed = []

    try:
        for index, raw_file in enumerate(
            raw_files,
            start=1,
        ):
            filename = raw_file.rstrip("/").split("/")[-1]

            # Remove compression and normal extension to create
            # the per-file feature directory.
            base_filename = filename

            if base_filename.endswith(".gz"):
                base_filename = base_filename[:-3]
            elif base_filename.endswith(".gzip"):
                base_filename = base_filename[:-5]

            base_filename = os.path.splitext(
                base_filename
            )[0]

            file_output_path = (
                output_path
                + base_filename
                + "/"
            )

            print()
            print()
            print("#" * 70)
            print(
                f"STAGE A FILE {index} OF {len(raw_files)}"
            )
            print("#" * 70)

            try:
                _run_single_file(
                    spark=spark,
                    input_path=raw_file,
                    output_path=file_output_path,
                    identity_mapping_folder=(
                        identity_mapping_folder
                    ),
                )

                successful.append(raw_file)

            except Exception as exc:
                print()
                print(
                    f"ERROR processing {raw_file}:"
                )
                print(exc)

                failed.append(
                    (
                        raw_file,
                        str(exc),
                    )
                )

        # ====================================================
        # Final Stage A status
        # ====================================================

        print()
        print("=" * 70)
        print("LogHawk Stage A Folder Run Completed")
        print("=" * 70)

        print(
            f"Total files:      {len(raw_files)}"
        )

        print(
            f"Successful:       {len(successful)}"
        )

        print(
            f"Failed:           {len(failed)}"
        )

        if failed:
            print()
            print("Failed files:")

            for path, error in failed:
                print()
                print(path)
                print(f"  {error}")

            raise RuntimeError(
                f"Stage A failed for "
                f"{len(failed)} file(s)."
            )

        print()
        print(
            "All raw files were successfully processed."
        )

        print()
        print(
            "Feature output folder:"
        )
        print(
            output_path
        )

        return output_path

    finally:
        spark.stop()


# ============================================================
# Standalone execution
# ============================================================

if __name__ == "__main__":

    INPUT_PATH = (
        "s3://loghawk-data/raw/2026-09-28/"
    )

    OUTPUT_PATH = (
        "s3://loghawk-data/features/2026-09-28/"
    )

    run(
        input_path=INPUT_PATH,
        output_path=OUTPUT_PATH,
    )

