# dynamic pyspark schema construction, identity mapping, and feature engineering for LogHawk logs stored in S3/S3-compatible storage.
"""
LogHawk - Generic PySpark Feature Engineering

Purpose:
    Read raw logs from S3/S3-compatible storage, load the
    corresponding LLM-generated identity mapping, dynamically
    construct the PySpark schema, derive entity_id, and perform
    deterministic feature engineering.

Example:

    Raw input:
        s3a://loghawk-data/raw/year=2026/month=09/day=23/sample_logs.json

    Identity mapping:
        s3a://loghawk-data/identitymapping/year=2026/month=09/day=23/
        identitymapping_sample_logs.json

    Feature output:
        s3a://loghawk-data/features/year=2026/month=09/day=23/

The identity mapping is generated by Ollama/Llama and contains
the priority order for identifying the entity that generated
each log event.
"""

from pathlib import Path
import json
import os
import re
from typing import Any

import s3fs

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    IntegerType,
    DoubleType,
)

import loghawk.config as config


# ============================================================
# Environment
# ============================================================

os.environ["JAVA_HOME"] = config.JAVA_HOME
os.environ["HADOOP_HOME"] = config.HADOOP_HOME

os.environ["PATH"] = (
    str(Path(config.JAVA_HOME) / "bin")
    + ";"
    + str(Path(config.HADOOP_HOME) / "bin")
    + ";"
    + os.environ.get("PATH", "")
)

os.environ["SPARK_LOCAL_HOSTNAME"] = "localhost"


# ============================================================
# Default paths
# ============================================================

INPUT_PATH = (
    "s3a://loghawk-data/raw/"
    "year=2026/month=09/day=23/sample_logs.json"
)

OUTPUT_PATH = (
    "s3a://loghawk-data/features/"
    "year=2026/month=09/day=23/"
)


# ============================================================
# Identity mapping configuration
# ============================================================

FALLBACK_ENTITY_ID = "unknown-entity"


# ============================================================
# S3 helper
# ============================================================

def create_s3_filesystem() -> s3fs.S3FileSystem:
    """
    Create an S3/S3-compatible filesystem for reading the
    identity mapping JSON.

    The same credentials/endpoint used by Spark are taken from
    LogHawk configuration.
    """

    return s3fs.S3FileSystem(
        key=config.LH_S3_ACCESS_KEY_ID,
        secret=config.LH_S3_SECRET_ACCESS_KEY,
        client_kwargs={
            "endpoint_url": config.LH_S3_ENDPOINT,
        },
    )


# ============================================================
# Convert s3a:// -> s3://
# ============================================================

def s3a_to_s3(path: str) -> str:
    """
    s3fs expects s3:// while Spark uses s3a://.
    """

    if path.startswith("s3a://"):
        return "s3://" + path[len("s3a://"):]

    if path.startswith("s3://"):
        return path

    raise ValueError(
        f"Unsupported S3 path: {path}. "
        "Expected s3a:// or s3://."
    )


# ============================================================
# Derive identity mapping path
# ============================================================

def derive_identity_mapping_path(
    raw_input_path: str,
) -> str:
    """
    Derive the identity mapping JSON path from the raw input path.

    Example:

        Raw:
        s3a://loghawk-data/raw/year=2026/month=09/day=23/sample_logs.json

        Mapping:
        s3a://loghawk-data/identitymapping/
        year=2026/month=09/day=23/
        identitymapping_sample_logs.json
    """

    if not (
        raw_input_path.startswith("s3a://")
        or raw_input_path.startswith("s3://")
    ):
        raise ValueError(
            "Raw input path must start with s3a:// or s3://"
        )

    # --------------------------------------------------------
    # Preserve the original scheme.
    # --------------------------------------------------------

    scheme = (
        "s3a://"
        if raw_input_path.startswith("s3a://")
        else "s3://"
    )

    path_without_scheme = re.sub(
        r"^s3a?://",
        "",
        raw_input_path,
    )

    # --------------------------------------------------------
    # Separate bucket and key.
    # --------------------------------------------------------

    parts = path_without_scheme.split("/", 1)

    if len(parts) != 2:
        raise ValueError(
            f"Invalid S3 path: {raw_input_path}"
        )

    bucket = parts[0]
    key = parts[1]

    # --------------------------------------------------------
    # IMPORTANT:
    #
    # Stage A may receive either:
    #
    # 1. a specific file
    #
    #    .../day=23/sample_logs.json
    #
    # 2. a directory
    #
    #    .../day=23/
    #
    # If it is a directory, there is no single mapping JSON
    # that can be derived from the directory name.
    # --------------------------------------------------------

    if key.endswith("/"):
        raise ValueError(
            "Identity mapping is source-file specific, but the "
            "input path is a directory:\n"
            f"{raw_input_path}\n\n"
            "Pass the individual raw input file path when using "
            "LLM-generated identity mappings."
        )

    key_parts = key.split("/")

    # --------------------------------------------------------
    # Locate raw directory.
    # --------------------------------------------------------

    try:
        raw_index = key_parts.index("raw")

    except ValueError as exc:
        raise ValueError(
            f"Could not locate 'raw' directory in:\n"
            f"{raw_input_path}"
        ) from exc

    remaining_parts = key_parts[raw_index + 1:]

    if not remaining_parts:
        raise ValueError(
            f"No input file found after /raw/:\n"
            f"{raw_input_path}"
        )

    input_filename = remaining_parts[-1]

    # --------------------------------------------------------
    # Remove compression extension.
    # --------------------------------------------------------

    base_filename = input_filename

    if base_filename.endswith(".gz"):
        base_filename = base_filename[:-3]

    elif base_filename.endswith(".gzip"):
        base_filename = base_filename[:-5]

    # --------------------------------------------------------
    # Remove original extension.
    #
    # sample_logs.json
    #     ->
    # sample_logs
    # --------------------------------------------------------

    base_filename = os.path.splitext(
        base_filename
    )[0]

    output_filename = (
        f"identitymapping_{base_filename}.json"
    )

    # --------------------------------------------------------
    # Preserve:
    #
    # year=2026
    # month=09
    # day=23
    # --------------------------------------------------------

    partition_parts = remaining_parts[:-1]

    output_key_parts = [
        "identitymapping",
        *partition_parts,
        output_filename,
    ]

    output_key = "/".join(output_key_parts)

    return f"{scheme}{bucket}/{output_key}"


# ============================================================
# Read identity mapping JSON
# ============================================================

def load_identity_mapping(
    mapping_path: str,
) -> dict[str, Any]:
    """
    Read the LLM-generated identity mapping JSON from S3.
    """

    filesystem_path = s3a_to_s3(mapping_path)

    print()
    print("=" * 70)
    print("Reading identity mapping")
    print("=" * 70)

    print("Mapping:", mapping_path)

    fs = create_s3_filesystem()

    if not fs.exists(filesystem_path):
        raise FileNotFoundError(
            "Identity mapping JSON was not found:\n"
            f"{mapping_path}\n\n"
            "Run the Ollama identity-mapping step first."
        )

    with fs.open(
        filesystem_path,
        "r",
        encoding="utf-8",
    ) as f:

        mapping_document = json.load(f)

    # --------------------------------------------------------
    # The Ollama program writes:
    #
    # {
    #   "source": {...},
    #   "identity_mapping": {
    #       ...
    #   }
    # }
    # --------------------------------------------------------

    if "identity_mapping" not in mapping_document:
        raise ValueError(
            "Invalid identity mapping JSON.\n"
            "Expected 'identity_mapping' section.\n"
            f"Path: {mapping_path}"
        )

    mapping = mapping_document["identity_mapping"]

    if not isinstance(mapping, dict):
        raise ValueError(
            "'identity_mapping' must be a JSON object."
        )

    return mapping


# ============================================================
# Validate identity mapping
# ============================================================

def validate_identity_mapping(
    mapping: dict[str, Any],
    available_columns: list[str],
) -> list[str]:
    """
    Validate the LLM-generated identity priority order against
    the actual raw input schema.

    Only columns that really exist in the input are allowed.

    Returns:
        Valid identity columns in priority order.
    """

    available = set(available_columns)

    priority_order = mapping.get(
        "priority_order",
        [],
    )

    if not isinstance(priority_order, list):
        raise ValueError(
            "identity_mapping.priority_order must be a list."
        )

    valid_columns = []

    for column in priority_order:

        if column in available:

            if column not in valid_columns:
                valid_columns.append(column)

        else:

            print(
                f"WARNING: Identity mapping contains column "
                f"'{column}', but it does not exist in the "
                f"raw input schema. Ignoring it."
            )

    # --------------------------------------------------------
    # If the LLM mapping contains identity_columns but omitted
    # something from priority_order, we can consider it as a
    # secondary candidate.
    # --------------------------------------------------------

    identity_columns = mapping.get(
        "identity_columns",
        [],
    )

    if isinstance(identity_columns, list):

        for column in identity_columns:

            if (
                column in available
                and column not in valid_columns
            ):
                valid_columns.append(column)

    return valid_columns


# ============================================================
# Construct dynamic Spark schema
# ============================================================

def construct_schema(
    inferred_schema: StructType,
    identity_columns: list[str],
) -> StructType:
    """
    Construct a Spark schema dynamically from the actual raw
    input schema.

    Identity columns are forced to StringType because they may
    originate from different source systems and formats.

    Common LogHawk fields receive predictable types where
    appropriate.

    Unknown/source-specific fields are preserved using their
    inferred Spark data types.
    """

    identity_set = set(identity_columns)

    fields = []

    for field in inferred_schema.fields:

        field_name = field.name

        # ----------------------------------------------------
        # Identity columns must be strings.
        # ----------------------------------------------------

        if field_name in identity_set:

            fields.append(
                StructField(
                    field_name,
                    StringType(),
                    True,
                )
            )

        # ----------------------------------------------------
        # Standard LogHawk fields.
        # ----------------------------------------------------

        elif field_name == "timestamp":

            fields.append(
                StructField(
                    field_name,
                    StringType(),
                    True,
                )
            )

        elif field_name == "level":

            fields.append(
                StructField(
                    field_name,
                    StringType(),
                    True,
                )
            )

        elif field_name == "message":

            fields.append(
                StructField(
                    field_name,
                    StringType(),
                    True,
                )
            )

        elif field_name == "exception":

            fields.append(
                StructField(
                    field_name,
                    StringType(),
                    True,
                )
            )

        elif field_name == "status_code":

            fields.append(
                StructField(
                    field_name,
                    IntegerType(),
                    True,
                )
            )

        # ----------------------------------------------------
        # Unknown source-specific columns retain their
        # inferred types.
        # ----------------------------------------------------

        else:

            fields.append(
                StructField(
                    field_name,
                    field.dataType,
                    field.nullable,
                )
            )

    return StructType(fields)


# ============================================================
# Construct entity_id expression
# ============================================================

def build_entity_id_expression(
    identity_columns: list[str],
):
    """
    Build the deterministic PySpark expression used to create
    entity_id from the LLM-generated priority order.
    """

    expressions = []

    for column in identity_columns:

        expressions.append(
            F.when(
                F.col(column).isNotNull()
                & (F.trim(F.col(column)) != ""),
                F.trim(F.col(column)),
            )
        )

    if not expressions:
        return F.lit(FALLBACK_ENTITY_ID)

    return F.coalesce(
        *expressions,
        F.lit(FALLBACK_ENTITY_ID),
    )


# ============================================================
# Main Stage A
# ============================================================

def run(
    input_path: str,
    output_path: str,
):
    """
    Run LogHawk Stage A feature engineering.

    Parameters
    ----------
    input_path:
        Raw S3/S3-compatible input path.

    output_path:
        Feature output path.
    """

    # --------------------------------------------------------
    # Derive corresponding identity mapping.
    # --------------------------------------------------------

    identity_mapping_path = (
        derive_identity_mapping_path(
            input_path
        )
    )

    # --------------------------------------------------------
    # Load identity mapping BEFORE creating entity_id.
    # --------------------------------------------------------

    mapping = load_identity_mapping(
        identity_mapping_path
    )

    print()
    print("LLM identity mapping:")
    print(
        json.dumps(
            mapping,
            indent=4,
        )
    )

    # --------------------------------------------------------
    # Start Spark.
    # --------------------------------------------------------

    spark = (
        SparkSession.builder
        .appName(
            "LogHawk-FeatureEngineering-S3"
        )
        .master("local[1]")
        .config(
            "spark.jars.packages",
            "org.apache.hadoop:hadoop-aws:3.3.4",
        )
        .config(
            "spark.hadoop.fs.s3a.impl",
            "org.apache.hadoop.fs.s3a.S3AFileSystem",
        )
        .config(
            "spark.hadoop.fs.s3a.endpoint",
            config.LH_S3_ENDPOINT,
        )
        .config(
            "spark.hadoop.fs.s3a.access.key",
            config.LH_S3_ACCESS_KEY_ID,
        )
        .config(
            "spark.hadoop.fs.s3a.secret.key",
            config.LH_S3_SECRET_ACCESS_KEY,
        )
        .config(
            "spark.hadoop.fs.s3a.path.style.access",
            "true",
        )
        .config(
            "spark.hadoop.fs.s3a.connection.ssl.enabled",
            "false",
        )
        .config(
            "spark.hadoop.fs.s3a.aws.credentials.provider",
            "org.apache.hadoop.fs.s3a."
            "SimpleAWSCredentialsProvider",
        )
        .config(
            "spark.hadoop.fs.s3a.connection.timeout",
            "60000",
        )
        .config(
            "spark.hadoop.fs.s3a.connection.establish.timeout",
            "60000",
        )
        .config(
            "spark.hadoop.fs.s3a.threads.keepalivetime",
            "60",
        )
        .config(
            "spark.hadoop.fs.s3a.multipart.purge",
            "false",
        )
        .getOrCreate()
    )

    spark.sparkContext.setLogLevel("WARN")

    try:

        print()
        print("=" * 70)
        print("LogHawk Stage A")
        print("=" * 70)

        print("Input :", input_path)
        print("Mapping:", identity_mapping_path)
        print("Output:", output_path)

        # ====================================================
        # Read raw JSON and infer actual source schema
        # ====================================================

        print()
        print("Inferring raw log schema from S3...")

        inferred_logs = (
            spark.read
            .option("samplingRatio", 0.1)
            .json(input_path)
        )
        print()
        print("Inferred schema:")
        inferred_logs.printSchema()

        inferred_schema = inferred_logs.schema
        available_columns = inferred_logs.columns

        print()
        print("Raw columns:")
        print(available_columns)

        # ====================================================
        # Validate LLM identity mapping
        # ====================================================

        identity_columns = validate_identity_mapping(
            mapping=mapping,
            available_columns=available_columns,
        )

        print()
        print("=" * 70)
        print("Validated identity mapping")
        print("=" * 70)

        if identity_columns:

            for index, column in enumerate(
                identity_columns,
                start=1,
            ):
                print(
                    f"{index}. {column}"
                )

        else:

            print(
                "No valid identity columns found."
            )

            print(
                f"Using fallback entity_id: "
                f"{FALLBACK_ENTITY_ID}"
            )

        # ====================================================
        # Construct the final PySpark schema
        # ====================================================

        schema = construct_schema(
            inferred_schema=inferred_schema,
            identity_columns=identity_columns,
        )

        print()
        print("=" * 70)
        print("Constructed PySpark schema")
        print("=" * 70)
  
        # ====================================================
        # Read raw logs again using constructed schema
        # ====================================================

        print()
        print("Reading raw logs using constructed schema...")

        logs = (
            spark.read
            .schema(schema)
            .json(input_path)
        )

        # ====================================================
        # Standardize common fields
        # ====================================================

        # ----------------------------------------------------
        # timestamp
        # ----------------------------------------------------

        if "timestamp" in logs.columns:

            logs = logs.withColumn(
                "event_time",
                F.to_timestamp(
                    F.col("timestamp")
                ),
            )

        else:

            raise ValueError(
                "Required field 'timestamp' was not found "
                "in the raw input."
            )

        # ----------------------------------------------------
        # level
        # ----------------------------------------------------

        if "level" in logs.columns:

            logs = logs.withColumn(
                "level",
                F.upper(
                    F.trim(
                        F.col("level")
                    )
                ),
            )

        else:

            logs = logs.withColumn(
                "level",
                F.lit("UNKNOWN"),
            )

        # ----------------------------------------------------
        # message
        # ----------------------------------------------------

        if "message" in logs.columns:

            logs = logs.withColumn(
                "message",
                F.coalesce(
                    F.col("message"),
                    F.lit(""),
                ),
            )

        else:

            logs = logs.withColumn(
                "message",
                F.lit(""),
            )

        # ----------------------------------------------------
        # exception
        # ----------------------------------------------------

        if "exception" in logs.columns:

            logs = logs.withColumn(
                "exception",
                F.coalesce(
                    F.col("exception"),
                    F.lit(""),
                ),
            )

        else:

            logs = logs.withColumn(
                "exception",
                F.lit(""),
            )

        # ----------------------------------------------------
        # status_code
        # ----------------------------------------------------

        if "status_code" in logs.columns:

            logs = logs.withColumn(
                "status_code",
                F.col("status_code").cast("int"),
            )

        else:

            logs = logs.withColumn(
                "status_code",
                F.lit(None).cast("int"),
            )

        # ====================================================
        # Normalize identity columns
        # ====================================================

        for column in identity_columns:

            logs = logs.withColumn(
                column,
                F.when(
                    F.col(column).isNotNull()
                    & (
                        F.trim(
                            F.col(column)
                        ) != ""
                    ),
                    F.trim(
                        F.col(column)
                    ),
                ).otherwise(None),
            )

        # ====================================================
        # Construct generic entity_id
        # ====================================================

        entity_id_expression = (
            build_entity_id_expression(
                identity_columns
            )
        )

        logs = logs.withColumn(
            "entity_id",
            entity_id_expression,
        )

        # ====================================================
        # Deterministic feature engineering
        # ====================================================

        logs = (
            logs

            # ------------------------------------------------
            # Log levels
            # ------------------------------------------------

            .withColumn(
                "is_info",
                (
                    F.col("level") == "INFO"
                ).cast("int"),
            )

            .withColumn(
                "is_warn",
                F.col("level")
                .isin(
                    "WARN",
                    "WARNING",
                )
                .cast("int"),
            )

            .withColumn(
                "is_error",
                (
                    F.col("level") == "ERROR"
                ).cast("int"),
            )

            # ------------------------------------------------
            # HTTP status
            # ------------------------------------------------

            .withColumn(
                "is_http_4xx",
                (
                    (F.col("status_code") >= 400)
                    & (F.col("status_code") < 500)
                ).cast("int"),
            )

            .withColumn(
                "is_http_5xx",
                (
                    (F.col("status_code") >= 500)
                    & (F.col("status_code") < 600)
                ).cast("int"),
            )

            # ------------------------------------------------
            # Timeout
            # ------------------------------------------------

            .withColumn(
                "is_timeout",
                F.when(
                    F.lower(
                        F.col("message")
                    ).contains("timeout"),
                    1,
                ).otherwise(0),
            )

            # ------------------------------------------------
            # Connection errors
            # ------------------------------------------------

            .withColumn(
                "is_connection_error",
                F.when(
                    F.lower(
                        F.col("message")
                    ).rlike(
                        "connection refused|"
                        "connection reset|"
                        "connection failed"
                    ),
                    1,
                ).otherwise(0),
            )

            # ------------------------------------------------
            # Authentication failures
            # ------------------------------------------------

            .withColumn(
                "is_auth_failure",
                F.when(
                    F.lower(
                        F.col("message")
                    ).rlike(
                        "authentication failed|"
                        "unauthorized|"
                        "invalid credentials|"
                        "login failed"
                    ),
                    1,
                ).otherwise(0),
            )
        )

        # ====================================================
        # Remove records with invalid timestamps
        # ====================================================

        logs = logs.filter(
            F.col("event_time").isNotNull()
        )

        # ====================================================
        # One-minute window
        # ====================================================

        logs = logs.withColumn(
            "window",
            F.window(
                F.col("event_time"),
                "1 minute",
            ),
        )

        # ====================================================
        # Aggregate by generic entity
        # ====================================================

        aggregation_expressions = []

        # ----------------------------------------------------
        # Preserve all identity metadata.
        #
        # This is useful for Stage C/D but these fields are
        # NOT part of the ML feature vector.
        # ----------------------------------------------------

        for column in identity_columns:

            aggregation_expressions.append(
                F.first(
                    column,
                    ignorenulls=True,
                ).alias(column)
            )

        # ----------------------------------------------------
        # Numeric features
        # ----------------------------------------------------

        aggregation_expressions.extend(
            [
                F.count("*").alias(
                    "total_log_count"
                ),

                F.sum("is_info").alias(
                    "info_count"
                ),

                F.sum("is_warn").alias(
                    "warning_count"
                ),

                F.sum("is_error").alias(
                    "error_count"
                ),

                F.sum("is_http_4xx").alias(
                    "http_4xx_count"
                ),

                F.sum("is_http_5xx").alias(
                    "http_5xx_count"
                ),

                F.sum("is_timeout").alias(
                    "timeout_count"
                ),

                F.sum(
                    "is_connection_error"
                ).alias(
                    "connection_error_count"
                ),

                F.sum(
                    "is_auth_failure"
                ).alias(
                    "authentication_failure_count"
                ),

                F.countDistinct(
                    F.when(
                        F.col("exception") != "",
                        F.col("exception"),
                    )
                ).alias(
                    "unique_exception_count"
                ),

                F.countDistinct(
                    F.when(
                        F.col("level") == "ERROR",
                        F.col("message"),
                    )
                ).alias(
                    "unique_error_message_count"
                ),
            ]
        )

        features = (
            logs
            .groupBy(
                "entity_id",
                "window",
            )
            .agg(
                *aggregation_expressions
            )
        )

        # ====================================================
        # Window timestamp
        # ====================================================

        features = (
            features
            .withColumn(
                "timestamp",
                F.col("window.start"),
            )
            .drop("window")
        )

        # ====================================================
        # Rates
        # ====================================================

        features = (
            features

            .withColumn(
                "error_rate",
                F.when(
                    F.col("total_log_count") > 0,
                    F.col("error_count")
                    / F.col("total_log_count"),
                ).otherwise(0.0),
            )

            .withColumn(
                "warning_rate",
                F.when(
                    F.col("total_log_count") > 0,
                    F.col("warning_count")
                    / F.col("total_log_count"),
                ).otherwise(0.0),
            )

            .withColumn(
                "http_5xx_rate",
                F.when(
                    F.col("total_log_count") > 0,
                    F.col("http_5xx_count")
                    / F.col("total_log_count"),
                ).otherwise(0.0),
            )

            .withColumn(
                "timeout_rate",
                F.when(
                    F.col("total_log_count") > 0,
                    F.col("timeout_count")
                    / F.col("total_log_count"),
                ).otherwise(0.0),
            )
        )

        # ====================================================
        # Build final output columns
        # ====================================================

        metadata_columns = [
            "timestamp",
            "entity_id",
        ]

        # ----------------------------------------------------
        # Preserve identity columns generated by LLM.
        # ----------------------------------------------------

        for column in identity_columns:

            if column not in metadata_columns:

                metadata_columns.append(column)

        feature_columns = [
            "total_log_count",
            "info_count",
            "warning_count",
            "error_count",
            "error_rate",
            "warning_rate",
            "http_4xx_count",
            "http_5xx_count",
            "http_5xx_rate",
            "timeout_count",
            "timeout_rate",
            "connection_error_count",
            "authentication_failure_count",
            "unique_exception_count",
            "unique_error_message_count",
        ]

        final_columns = (
            metadata_columns
            + feature_columns
        )

        features = features.select(
            *final_columns
        )

        # ====================================================
        # Display results
        # ====================================================

        print()
        print("=" * 70)
        print("Generated feature dataset")
        print("=" * 70)

        features.orderBy(
            F.col("timestamp")
        ).show(
            20,
            truncate=False,
        )

        # ====================================================
        # Write features
        # ====================================================

        print()
        print(
            "Writing feature data to S3..."
        )

        # ----------------------------------------------------
        # Do NOT partition by entity_id.
        #
        # entity_id can be high-cardinality and create many
        # small files.
        # ----------------------------------------------------

        (
            features
            .write
            .mode("overwrite")
            .parquet(output_path)
        )

        # ====================================================
        # Completed
        # ====================================================

        print()
        print("=" * 70)
        print("LogHawk feature generation completed")
        print("=" * 70)

        print()
        print("Raw input:")
        print(input_path)

        print()
        print("Identity mapping:")
        print(identity_mapping_path)

        print()
        print("Entity priority:")
        print(identity_columns)

        print()
        print("Feature output:")
        print(output_path)

        print()

        return output_path

    finally:

        spark.stop()


# ============================================================
# Standalone execution
# ============================================================

if __name__ == "__main__":

    run(
        input_path=INPUT_PATH,
        output_path=OUTPUT_PATH,
    )