# separate train and raw paths, and generate identity mapping for each file in the raw path.
"""
LogHawk - Generic PySpark Feature Engineering

Purpose:
    Read raw logs from S3/S3-compatible storage, load the
    corresponding LLM-generated identity mapping, dynamically
    construct the PySpark schema, derive entity_id, and perform
    deterministic feature engineering.

Example:

    Raw input:
        s3a://loghawk-data/raw/year=2026/month=09/day=23/sample_logs.json

    Identity mapping:
        s3a://loghawk-data/identitymapping/year=2026/month=09/day=23/
        identitymapping_sample_logs.json

    Feature output:
        s3a://loghawk-data/features/year=2026/month=09/day=23/

The identity mapping is generated by Ollama/Llama and contains
the priority order for identifying the entity that generated
each log event.
"""

from pathlib import Path
import json
import os
import re
import shutil
import tempfile
from typing import Any
from urllib.parse import urlparse

import boto3
import s3fs
from botocore.config import Config as BotoConfig

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    IntegerType,
    DoubleType,
)

import loghawk.config as config


# ============================================================
# Environment
# ============================================================

if config.LH_OS_FAMILY == "WINDOWS":
    java_home = config.LH_JAVA_HOME_WINDOWS
    hadoop_home = config.LH_HADOOP_HOME_WINDOWS
    os.environ["JAVA_HOME"] = java_home
    os.environ["HADOOP_HOME"] = hadoop_home
    path_entries = [
        str(Path(java_home) / "bin"),
        str(Path(hadoop_home) / "bin"),
        os.environ.get("PATH", ""),
    ]
else:  # Linux and Mac
    java_home = config.LH_JAVA_HOME
    if not java_home:
        raise ValueError("Set JAVA_HOME in .env for Linux or Mac.")
    os.environ["JAVA_HOME"] = java_home
    path_entries = [
        str(Path(java_home) / "bin"),
        os.environ.get("PATH", ""),
    ]

os.environ["PATH"] = os.pathsep.join(path_entries)

os.environ["SPARK_LOCAL_HOSTNAME"] = "localhost"


# ============================================================
# Default paths
# ============================================================

INPUT_PATH = (
    "s3://loghawk-data/raw/2026-09-28/"
)

OUTPUT_PATH = (
    "s3://loghawk-data/features/2026-09-28/"
)


# ============================================================
# Identity mapping configuration
# ============================================================

FALLBACK_ENTITY_ID = "unknown-entity"


# ============================================================
# S3 helper
# ============================================================

def to_spark_s3_path(path: str) -> str:
    if path.startswith("s3://"):
        return "s3a://" + path[len("s3://"):]
    return path

def create_s3_filesystem() -> s3fs.S3FileSystem:
    """
    Create an S3/S3-compatible filesystem for reading the
    identity mapping JSON.

    The same credentials/endpoint used by Spark are taken from
    LogHawk configuration.
    """

    return s3fs.S3FileSystem(
        key=config.LH_S3_ACCESS_KEY_ID,
        secret=config.LH_S3_SECRET_ACCESS_KEY,
        client_kwargs={
            "endpoint_url": config.LH_S3_ENDPOINT,
        },
    )


def s3_select_enabled(path: str) -> bool:
    """S3 Select is limited here to enabled, uncompressed JSON objects."""
    filename = path.rstrip("/").lower()
    phase = path.rstrip("/").split("/")[-2].lower()
    phase_use = {
        "train": config.LH_S3_SELECT_USE_TRAIN_PHASE,
        "raw": config.LH_S3_SELECT_USE_DETECT_PHASE,
    }.get(phase, False)
    return (
        config.LH_S3_SELECT_SUPPORTED
        and phase_use
        and not filename.endswith((".gz", ".gzip"))
        and filename.endswith((".json", ".jsonl"))
    )


def materialize_s3_select_jsonl(
    input_path: str,
    output_path: str,
    level_column: str | None,
) -> str:
    """Write S3 Select's streamed JSONL records to a temporary local file."""
    parsed = urlparse(s3a_to_s3(input_path))
    if parsed.scheme != "s3" or not parsed.netloc or not parsed.path:
        raise ValueError(f"Invalid S3 object path: {input_path}")

    filters = config.LH_S3_SELECT_RECORD_FILTER_LIST
    expression = "SELECT * FROM S3Object s"
    if filters:
        if not level_column:
            raise ValueError(
                "S3 Select record filtering is enabled, but no valid log-level "
                "column is mapped. Set LH_S3_SELECT_RECORD_FILTER=ALL or "
                "provide a valid field mapping."
            )
        identifier = 's."' + level_column.replace('"', '""') + '"'
        filter_values = [
            alias
            for value in filters
            for alias in (("WARN", "WARNING") if value == "WARN" else (value,))
        ]
        literals = ", ".join(
            "'" + value.replace("'", "''") + "'"
            for value in filter_values
        )
        expression += f" WHERE upper(cast({identifier} as varchar)) IN ({literals})"

    client = boto3.client(
        "s3",
        endpoint_url=config.LH_S3_ENDPOINT,
        aws_access_key_id=config.LH_S3_ACCESS_KEY_ID,
        aws_secret_access_key=config.LH_S3_SECRET_ACCESS_KEY,
        region_name=config.LH_S3_REGION,
        config=BotoConfig(
            signature_version="s3v4",
            s3={"addressing_style": "path"},
        ),
    )
    response = client.select_object_content(
        Bucket=parsed.netloc,
        Key=parsed.path.lstrip("/"),
        ExpressionType="SQL",
        Expression=expression,
        InputSerialization={
            "JSON": {"Type": "LINES"},
            "CompressionType": "NONE",
        },
        OutputSerialization={
            "JSON": {"RecordDelimiter": "\n"},
        },
    )

    ended = False
    selected_row_count = 0
    pending = b""
    with open(output_path, "wb") as output_file:
        for event in response["Payload"]:
            if "Records" in event:
                payload = event["Records"]["Payload"]
                output_file.write(payload)
                lines = (pending + payload).split(b"\n")
                selected_row_count += sum(
                    1 for line in lines[:-1] if line.strip()
                )
                pending = lines[-1]
            elif "End" in event:
                ended = True

        if pending.strip():
            selected_row_count += 1

        if not ended:
            raise RuntimeError(
                f"S3 Select stream ended without an End event: {input_path}"
            )
        output_file.flush()
        output_file.seek(0, os.SEEK_END)
        if output_file.tell() and not _file_ends_with_newline(output_path):
            output_file.write(b"\n")

    if os.path.getsize(output_path) == 0:
        raise ValueError(
            "S3 Select returned no records for "
            f"{input_path} using filter {config.LH_S3_SELECT_RECORD_FILTER!r}"
        )
    print(f"Rows returned by S3 Select filter: {selected_row_count}")
    return Path(output_path).resolve().as_uri()


def _file_ends_with_newline(path: str) -> bool:
    with open(path, "rb") as input_file:
        input_file.seek(-1, os.SEEK_END)
        return input_file.read(1) == b"\n"


# ============================================================
# Convert s3a:// -> s3://
# ============================================================

def s3a_to_s3(path: str) -> str:
    """
    s3fs expects s3:// while Spark uses s3a://.
    """

    if path.startswith("s3a://"):
        return "s3://" + path[len("s3a://"):]

    if path.startswith("s3://"):
        return path

    raise ValueError(
        f"Unsupported S3 path: {path}. "
        "Expected s3a:// or s3://."
    )


# ============================================================
# Derive identity mapping path
# ============================================================

def normalize_s3_folder(path: str) -> str:
    """Ensure an S3 folder path ends with '/'."""
    if not (path.startswith("s3://") or path.startswith("s3a://")):
        raise ValueError(
            f"Unsupported S3 path: {path}. "
            "Expected s3:// or s3a://."
        )

    return path if path.endswith("/") else path + "/"


def derive_identity_mapping_folder(
    raw_input_folder: str,
) -> str:
    """
    Derive the phase-specific mapping root from:
        s3://bucket/<batch-folder>/{train|raw}/
    """
    raw_input_folder = normalize_s3_folder(raw_input_folder)

    scheme = (
        "s3a://"
        if raw_input_folder.startswith("s3a://")
        else "s3://"
    )

    path_without_scheme = re.sub(
        r"^s3a?://",
        "",
        raw_input_folder,
    )

    parts = path_without_scheme.split("/", 1)

    if len(parts) != 2:
        raise ValueError(
            f"Invalid S3 path: {raw_input_folder}"
        )

    bucket = parts[0]
    key = parts[1]

    key_parts = [p for p in key.split("/") if p]

    if len(key_parts) < 2 or key_parts[-1] not in {"train", "raw"}:
        raise ValueError(
            "Input folder must end in '/train/' or '/raw/':\n"
            f"{raw_input_folder}"
        )

    phase = key_parts[-1]
    batch_parts = key_parts[:-1]

    output_key = "/".join(
        [*batch_parts, "identitymapping", phase]
    ) + "/"

    return f"{scheme}{bucket}/{output_key}"


def derive_identity_mapping_path(
    raw_input_path: str,
    identity_mapping_folder: str | None = None,
) -> str:
    """
    Derive the identity mapping file for one raw input file.

    Example:

        Raw:
            s3://loghawk-data/raw/2026-09-28/container_logs.json

        Mapping:
            s3://loghawk-data/identitymapping/2026-09-28/
            identitymapping_container_logs.json
    """
    raw_input_path = raw_input_path.rstrip("/")

    if not (
        raw_input_path.startswith("s3://")
        or raw_input_path.startswith("s3a://")
    ):
        raise ValueError(
            "Raw input path must start with s3:// or s3a://"
        )

    if raw_input_path.endswith("/"):
        raise ValueError(
            "derive_identity_mapping_path() expects a file path, "
            "not a directory."
        )

    if identity_mapping_folder is None:
        # Derive mapping folder from the raw file path.
        path_without_scheme = re.sub(
            r"^s3a?://",
            "",
            raw_input_path,
        )
        parts = path_without_scheme.split("/", 1)

        if len(parts) != 2:
            raise ValueError(
                f"Invalid S3 path: {raw_input_path}"
            )

        bucket = parts[0]
        key = parts[1]
        key_parts = [p for p in key.split("/") if p]

        if len(key_parts) < 2 or key_parts[-2] not in {"train", "raw"}:
            raise ValueError(
                "Raw input file must be under a '/train/' or '/raw/' folder:\n"
                f"{raw_input_path}"
            )

        phase = key_parts[-2]
        batch_parts = key_parts[:-2]

        scheme = (
            "s3a://"
            if raw_input_path.startswith("s3a://")
            else "s3://"
        )

        identity_mapping_folder = (
            f"{scheme}{bucket}/"
            + "/".join([*batch_parts, "identitymapping", phase])
            + "/"
        )

    identity_mapping_folder = normalize_s3_folder(
        identity_mapping_folder
    )

    input_filename = raw_input_path.split("/")[-1]
    base_filename = input_file_stem(input_filename)
    group_name = source_group_name(input_filename)

    output_filename = (
        f"identitymapping_{base_filename}.json"
    )

    return identity_mapping_folder + group_name + "/" + output_filename


def input_file_stem(filename: str) -> str:
    """Remove one supported raw-file extension, including compound gzip suffixes."""
    supported_extensions = (
        ".jsonl.gz",
        ".json.gz",
        ".log.gz",
        ".jsonl",
        ".json",
        ".log",
    )
    lowered = filename.lower()
    for extension in supported_extensions:
        if lowered.endswith(extension):
            return filename[:-len(extension)]
    return os.path.splitext(filename)[0]


def source_group_name(filename: str) -> str:
    """Strip a trailing numeric sequence only when preceded by '_' or '-'."""
    stem = input_file_stem(filename)
    match = re.fullmatch(r"(.+)[_-]\d+", stem)
    return match.group(1) if match else stem


def list_raw_files(
    raw_input_folder: str,
    fs: s3fs.S3FileSystem,
) -> list[str]:
    """
    Enumerate supported raw log files directly under the input folder.
    """
    raw_input_folder = normalize_s3_folder(raw_input_folder)

    filesystem_path = s3a_to_s3(raw_input_folder)

    entries = fs.ls(
        filesystem_path,
        detail=True,
    )

    raw_files = []

    supported_extensions = (
        ".json",
        ".json.gz",
        ".jsonl",
        ".jsonl.gz",
        ".log",
        ".log.gz",
    )

    for entry in entries:
        if isinstance(entry, dict):
            entry_name = entry["name"]
            if entry.get("type") == "directory":
                continue
        else:
            entry_name = entry

        filename = entry_name.rstrip("/").split("/")[-1]

        if not filename:
            continue

        if filename.startswith("_") or filename.startswith("."):
            continue

        if not filename.lower().endswith(supported_extensions):
            print(
                f"Skipping unsupported file: {filename}"
            )
            continue

        raw_files.append(
            "s3://" + entry_name
            if not entry_name.startswith("s3://")
            else entry_name
        )

    raw_files.sort()
    return raw_files


# ============================================================
# Read identity mapping JSON
# ============================================================

def load_identity_mapping(
    mapping_path: str,
) -> dict[str, Any]:
    """
    Read the complete identity and field mapping JSON from S3.
    """

    filesystem_path = s3a_to_s3(mapping_path)

    print()
    print("=" * 70)
    print("Reading identity mapping")
    print("=" * 70)

    print("Mapping:", mapping_path)

    fs = create_s3_filesystem()

    if not fs.exists(filesystem_path):
        raise FileNotFoundError(
            "Identity mapping JSON was not found:\n"
            f"{mapping_path}\n\n"
            "Run the Ollama identity-mapping step first."
        )

    with fs.open(
        filesystem_path,
        "r",
        encoding="utf-8",
    ) as f:

        mapping_document = json.load(f)

    # --------------------------------------------------------
    # The Ollama program writes:
    #
    # {
    #   "source": {...},
    #   "identity_mapping": {...},
    #   "field_mapping": {...}
    # }
    # --------------------------------------------------------

    if "identity_mapping" not in mapping_document:
        raise ValueError(
            "Invalid identity mapping JSON.\n"
            "Expected 'identity_mapping' section.\n"
            f"Path: {mapping_path}"
        )

    mapping = mapping_document["identity_mapping"]

    if not isinstance(mapping, dict):
        raise ValueError(
            "'identity_mapping' must be a JSON object."
        )

    return mapping_document


# ============================================================
# Validate identity mapping
# ============================================================

def validate_identity_mapping(
    mapping: dict[str, Any],
    available_columns: list[str],
) -> list[str]:
    """
    Validate the LLM-generated identity priority order against
    the actual raw input schema.

    Only columns that really exist in the input are allowed.

    Returns:
        Valid identity columns in priority order.
    """

    available = set(available_columns)

    priority_order = mapping.get(
        "priority_order",
        [],
    )

    if not isinstance(priority_order, list):
        raise ValueError(
            "identity_mapping.priority_order must be a list."
        )

    valid_columns = []

    for column in priority_order:

        if column in available:

            if column not in valid_columns:
                valid_columns.append(column)

        else:

            print(
                f"WARNING: Identity mapping contains column "
                f"'{column}', but it does not exist in the "
                f"raw input schema. Ignoring it."
            )

    # --------------------------------------------------------
    # If the LLM mapping contains identity_columns but omitted
    # something from priority_order, we can consider it as a
    # secondary candidate.
    # --------------------------------------------------------

    identity_columns = mapping.get(
        "identity_columns",
        [],
    )

    if isinstance(identity_columns, list):

        for column in identity_columns:

            if (
                column in available
                and column not in valid_columns
            ):
                valid_columns.append(column)

    return valid_columns


FIELD_ROLE_FALLBACKS = {
    "timestamp_column": "timestamp",
    "level_column": "level",
    "message_column": "message",
    "status_code_column": "status_code",
    "exception_column": "exception",
}


def validate_field_mapping(
    field_mapping: dict[str, Any] | None,
    available_columns: list[str],
) -> dict[str, str | None]:
    """Resolve field roles against the source schema, including legacy names."""
    if not isinstance(field_mapping, dict):
        field_mapping = {}
    available = set(available_columns)
    resolved = {}

    for role, fallback_column in FIELD_ROLE_FALLBACKS.items():
        column = field_mapping.get(role)

        if column is not None and (
            not isinstance(column, str)
            or column not in available
        ):
            print(
                f"WARNING: Field mapping {role}='{column}' is not in "
                "the source schema; checking the legacy field name."
            )
            column = None

        if column is None and fallback_column in available:
            column = fallback_column

        resolved[role] = column

    if resolved["timestamp_column"] is None:
        raise ValueError(
            "No valid timestamp field is mapped. "
            f"Available columns: {sorted(available)}"
        )

    return resolved


# ============================================================
# Construct dynamic Spark schema
# ============================================================

def construct_schema(
    inferred_schema: StructType,
    identity_columns: list[str],
    field_mapping: dict[str, str | None],
) -> StructType:
    """
    Construct a Spark schema dynamically from the actual raw
    input schema.

    Identity columns are forced to StringType because they may
    originate from different source systems and formats.

    Common LogHawk fields receive predictable types where
    appropriate.

    Unknown/source-specific fields are preserved using their
    inferred Spark data types.
    """

    identity_set = set(identity_columns)
    role_types = {
        field_mapping["timestamp_column"]: StringType(),
        field_mapping["level_column"]: StringType(),
        field_mapping["message_column"]: StringType(),
        field_mapping["exception_column"]: StringType(),
        field_mapping["status_code_column"]: IntegerType(),
    }

    fields = []

    for field in inferred_schema.fields:

        field_name = field.name

        # ----------------------------------------------------
        # Identity columns must be strings.
        # ----------------------------------------------------

        if field_name in identity_set:

            fields.append(
                StructField(
                    field_name,
                    StringType(),
                    True,
                )
            )

        elif field_name in role_types and role_types[field_name] is not None:
            fields.append(
                StructField(
                    field_name,
                    role_types[field_name],
                    True,
                )
            )

        # ----------------------------------------------------
        # Unknown source-specific columns retain their
        # inferred types.
        # ----------------------------------------------------

        else:

            fields.append(
                StructField(
                    field_name,
                    field.dataType,
                    field.nullable,
                )
            )

    return StructType(fields)


# ============================================================
# Construct entity_id expression
# ============================================================

def build_entity_id_expression(
    identity_columns: list[str],
):
    """
    Build the deterministic PySpark expression used to create
    entity_id from the LLM-generated priority order.
    """

    expressions = []

    for column in identity_columns:

        expressions.append(
            F.when(
                F.col(column).isNotNull()
                & (F.trim(F.col(column)) != ""),
                F.trim(F.col(column)),
            )
        )

    if not expressions:
        return F.lit(FALLBACK_ENTITY_ID)

    return F.coalesce(
        *expressions,
        F.lit(FALLBACK_ENTITY_ID),
    )


# ============================================================
# Grouped Stage A
# ============================================================

def _read_normalized_file(
    spark: SparkSession,
    input_path: str,
    identity_mapping_folder: str,
    select_temp_dir: str,
):
    """Read one source file, apply its mapping, and normalize role columns."""
    mapping_path = derive_identity_mapping_path(
        input_path,
        identity_mapping_folder,
    )
    mapping_document = load_identity_mapping(mapping_path)

    spark_input_path = to_spark_s3_path(input_path)
    if s3_select_enabled(input_path):
        available_columns = mapping_document.get("source", {}).get(
            "column_names", []
        )
        if not isinstance(available_columns, list) or not available_columns:
            raise ValueError(
                f"Mapping has no source.column_names: {mapping_path}"
            )
        inferred_schema = StructType([
            StructField(str(column), StringType(), True)
            for column in available_columns
        ])
    else:
        inferred = spark.read.option("samplingRatio", 0.1).json(
            spark_input_path
        )
        inferred_schema = inferred.schema
        available_columns = inferred.columns

    identity_columns = validate_identity_mapping(
        mapping_document["identity_mapping"],
        available_columns,
    )
    field_mapping = validate_field_mapping(
        mapping_document.get("field_mapping"),
        available_columns,
    )

    if s3_select_enabled(input_path):
        local_path = os.path.join(
            select_temp_dir,
            os.path.basename(input_path.rstrip("/")) + ".selected.jsonl",
        )
        spark_input_path = materialize_s3_select_jsonl(
            input_path,
            local_path,
            field_mapping["level_column"],
        )

    logs = spark.read.schema(
        construct_schema(
            inferred_schema,
            identity_columns,
            field_mapping,
        )
    ).json(spark_input_path)

    timestamp_source = field_mapping["timestamp_column"]
    logs = logs.withColumn(
        "event_time",
        F.to_timestamp(F.col(timestamp_source)),
    )

    level_source = field_mapping["level_column"]
    level_value = (
        F.col(level_source).cast("string")
        if level_source else F.lit("UNKNOWN")
    )
    logs = logs.withColumn(
        "level",
        F.upper(F.trim(F.coalesce(level_value, F.lit("UNKNOWN")))),
    )

    message_source = field_mapping["message_column"]
    message_value = (
        F.col(message_source).cast("string")
        if message_source else F.lit("")
    )
    logs = logs.withColumn("message", F.coalesce(message_value, F.lit("")))

    exception_source = field_mapping["exception_column"]
    exception_value = (
        F.col(exception_source).cast("string")
        if exception_source else F.lit("")
    )
    logs = logs.withColumn(
        "exception",
        F.coalesce(exception_value, F.lit("")),
    )

    status_source = field_mapping["status_code_column"]
    status_value = (
        F.col(status_source).cast("int")
        if status_source else F.lit(None).cast("int")
    )
    logs = logs.withColumn("status_code", status_value)

    for column in identity_columns:
        logs = logs.withColumn(
            column,
            F.when(
                F.col(column).isNotNull()
                & (F.trim(F.col(column)) != ""),
                F.trim(F.col(column)),
            ).otherwise(None),
        )

    logs = logs.withColumn(
        "entity_id",
        build_entity_id_expression(identity_columns),
    )

    selected_columns = list(dict.fromkeys([
        "event_time",
        "entity_id",
        *identity_columns,
        "level",
        "message",
        "exception",
        "status_code",
    ]))
    return logs.select(*selected_columns), identity_columns


def _build_group_features(logs, identity_columns: list[str], group_name: str):
    """Aggregate normalized rows from every file in one source group."""
    logs = (
        logs
        .withColumn("is_info", (F.col("level") == "INFO").cast("int"))
        .withColumn(
            "is_warn",
            F.col("level").isin("WARN", "WARNING").cast("int"),
        )
        .withColumn("is_error", (F.col("level") == "ERROR").cast("int"))
        .withColumn(
            "is_http_4xx",
            ((F.col("status_code") >= 400) & (F.col("status_code") < 500)).cast("int"),
        )
        .withColumn(
            "is_http_5xx",
            ((F.col("status_code") >= 500) & (F.col("status_code") < 600)).cast("int"),
        )
        .withColumn(
            "is_timeout",
            F.lower(F.col("message")).contains("timeout").cast("int"),
        )
        .withColumn(
            "is_connection_error",
            F.lower(F.col("message")).rlike(
                "connection refused|connection reset|connection failed"
            ).cast("int"),
        )
        .withColumn(
            "is_auth_failure",
            F.lower(F.col("message")).rlike(
                "authentication failed|unauthorized|invalid credentials|login failed"
            ).cast("int"),
        )
        .filter(F.col("event_time").isNotNull())
        .withColumn("window", F.window(F.col("event_time"), "1 minute"))
    )

    aggregations = [
        F.first(column, ignorenulls=True).alias(column)
        for column in identity_columns
    ]
    aggregations.extend([
        F.count("*").alias("total_log_count"),
        F.sum("is_info").alias("info_count"),
        F.sum("is_warn").alias("warning_count"),
        F.sum("is_error").alias("error_count"),
        F.sum("is_http_4xx").alias("http_4xx_count"),
        F.sum("is_http_5xx").alias("http_5xx_count"),
        F.sum("is_timeout").alias("timeout_count"),
        F.sum("is_connection_error").alias("connection_error_count"),
        F.sum("is_auth_failure").alias("authentication_failure_count"),
        F.countDistinct(
            F.when(F.col("exception") != "", F.col("exception"))
        ).alias("unique_exception_count"),
        F.countDistinct(
            F.when(F.col("level") == "ERROR", F.col("message"))
        ).alias("unique_error_message_count"),
    ])

    features = logs.groupBy("entity_id", "window").agg(*aggregations)
    features = (
        features
        .withColumn("timestamp", F.col("window.start"))
        .drop("window")
        .withColumn("source_group", F.lit(group_name))
    )

    for name, numerator in (
        ("error_rate", "error_count"),
        ("warning_rate", "warning_count"),
        ("http_5xx_rate", "http_5xx_count"),
        ("timeout_rate", "timeout_count"),
    ):
        features = features.withColumn(
            name,
            F.when(
                F.col("total_log_count") > 0,
                F.col(numerator) / F.col("total_log_count"),
            ).otherwise(0.0),
        )

    feature_columns = [
        "total_log_count", "info_count", "warning_count", "error_count",
        "error_rate", "warning_rate", "http_4xx_count", "http_5xx_count",
        "http_5xx_rate", "timeout_count", "timeout_rate",
        "connection_error_count", "authentication_failure_count",
        "unique_exception_count", "unique_error_message_count",
    ]
    metadata = ["timestamp", "entity_id", "source_group", *identity_columns]
    return features.select(*list(dict.fromkeys(metadata + feature_columns)))


# ============================================================
# Main Stage A
# ============================================================

def _run_single_file(
    spark: SparkSession,
    input_path: str,
    output_path: str,
    identity_mapping_folder: str,
    select_temp_dir: str,
):
    """
    Process exactly one raw file.

    The file gets its own identity mapping and its own Parquet
    dataset under:

        features/<date>/<input_filename>/
    """

    identity_mapping_path = derive_identity_mapping_path(
        input_path,
        identity_mapping_folder,
    )

    mapping_document = load_identity_mapping(
        identity_mapping_path
    )

    print()
    print("=" * 70)
    print("LogHawk Stage A - Processing File")
    print("=" * 70)

    print("Input :", input_path)
    print("Mapping:", identity_mapping_path)
    print("Output:", output_path)

    # ========================================================
    # Read raw JSON and infer actual source schema
    # ========================================================

    spark_input_path = to_spark_s3_path(input_path)
    spark_output_path = to_spark_s3_path(output_path)

    if s3_select_enabled(input_path):
        # Mapping metadata already contains the sampled source columns. Use
        # it to avoid scanning the raw object with Spark before the Select
        # request. Role and identity fields are explicitly typed below.
        available_columns = mapping_document.get("source", {}).get(
            "column_names",
            [],
        )
        if not isinstance(available_columns, list) or not available_columns:
            raise ValueError(
                "S3 Select requires source.column_names in the identity "
                f"mapping: {identity_mapping_path}"
            )
        inferred_schema = StructType(
            [
                StructField(str(column), StringType(), True)
                for column in available_columns
            ]
        )
        print("Using mapping source columns for S3 Select schema:")
        print(available_columns)
    else:
        print()
        print("Inferring raw log schema from S3...")

        inferred_logs = (
            spark.read
            .option("samplingRatio", 0.1)
            .json(spark_input_path)
        )

        print()
        print("Inferred schema:")
        inferred_logs.printSchema()

        inferred_schema = inferred_logs.schema
        available_columns = inferred_logs.columns

        print()
        print("Raw columns:")
        print(available_columns)

    # ========================================================
    # Validate LLM identity mapping
    # ========================================================

    identity_columns = validate_identity_mapping(
        mapping=mapping_document["identity_mapping"],
        available_columns=available_columns,
    )

    field_mapping = validate_field_mapping(
        mapping_document.get("field_mapping"),
        available_columns,
    )

    if s3_select_enabled(input_path):
        print(
            "Reading records through RustFS S3 Select; filter:",
            config.LH_S3_SELECT_RECORD_FILTER,
        )
        filename = os.path.basename(input_path.rstrip("/"))
        selected_local_path = os.path.join(
            select_temp_dir,
            f"{filename}.selected.jsonl",
        )
        spark_input_path = materialize_s3_select_jsonl(
            input_path=input_path,
            output_path=selected_local_path,
            level_column=field_mapping["level_column"],
        )
    else:
        print(
            "S3 Select disabled or unsupported for this file; "
            "using the existing Spark S3 reader."
        )

    print()
    print("=" * 70)
    print("Validated identity mapping")
    print("=" * 70)

    if identity_columns:
        for index, column in enumerate(
            identity_columns,
            start=1,
        ):
            print(
                f"{index}. {column}"
            )
    else:
        print(
            "No valid identity columns found."
        )
        print(
            f"Using fallback entity_id: "
            f"{FALLBACK_ENTITY_ID}"
        )

    # ========================================================
    # Construct final PySpark schema
    # ========================================================

    schema = construct_schema(
        inferred_schema=inferred_schema,
        identity_columns=identity_columns,
        field_mapping=field_mapping,
    )

    # ========================================================
    # Read raw logs using constructed schema
    # ========================================================

    print()
    print("Reading raw logs using constructed schema...")

    logs = (
        spark.read
        .schema(schema)
        .json(spark_input_path)
    )

    # ========================================================
    # Standardize common fields
    # ========================================================

    timestamp_source = field_mapping["timestamp_column"]
    logs = logs.withColumn(
        "event_time",
        F.to_timestamp(F.col(timestamp_source)),
    )

    level_source = field_mapping["level_column"]
    level_value = (
        F.col(level_source).cast("string")
        if level_source
        else F.lit("UNKNOWN")
    )
    logs = logs.withColumn(
        "level",
        F.upper(F.trim(F.coalesce(level_value, F.lit("UNKNOWN")))),
    )

    message_source = field_mapping["message_column"]
    message_value = (
        F.col(message_source).cast("string")
        if message_source
        else F.lit("")
    )
    logs = logs.withColumn(
        "message",
        F.coalesce(message_value, F.lit("")),
    )

    exception_source = field_mapping["exception_column"]
    exception_value = (
        F.col(exception_source).cast("string")
        if exception_source
        else F.lit("")
    )
    logs = logs.withColumn(
        "exception",
        F.coalesce(exception_value, F.lit("")),
    )

    status_source = field_mapping["status_code_column"]
    status_value = (
        F.col(status_source).cast("int")
        if status_source
        else F.lit(None).cast("int")
    )
    logs = logs.withColumn("status_code", status_value)

    # ========================================================
    # Normalize identity columns
    # ========================================================

    for column in identity_columns:
        logs = logs.withColumn(
            column,
            F.when(
                F.col(column).isNotNull()
                & (
                    F.trim(
                        F.col(column)
                    ) != ""
                ),
                F.trim(
                    F.col(column)
                ),
            ).otherwise(None),
        )

    # ========================================================
    # Construct generic entity_id
    # ========================================================

    entity_id_expression = (
        build_entity_id_expression(
            identity_columns
        )
    )

    logs = logs.withColumn(
        "entity_id",
        entity_id_expression,
    )

    # ========================================================
    # Deterministic feature engineering
    # ========================================================

    logs = (
        logs

        .withColumn(
            "is_info",
            (
                F.col("level") == "INFO"
            ).cast("int"),
        )

        .withColumn(
            "is_warn",
            F.col("level")
            .isin(
                "WARN",
                "WARNING",
            )
            .cast("int"),
        )

        .withColumn(
            "is_error",
            (
                F.col("level") == "ERROR"
            ).cast("int"),
        )

        .withColumn(
            "is_http_4xx",
            (
                (F.col("status_code") >= 400)
                & (F.col("status_code") < 500)
            ).cast("int"),
        )

        .withColumn(
            "is_http_5xx",
            (
                (F.col("status_code") >= 500)
                & (F.col("status_code") < 600)
            ).cast("int"),
        )

        .withColumn(
            "is_timeout",
            F.when(
                F.lower(
                    F.col("message")
                ).contains("timeout"),
                1,
            ).otherwise(0),
        )

        .withColumn(
            "is_connection_error",
            F.when(
                F.lower(
                    F.col("message")
                ).rlike(
                    "connection refused|"
                    "connection reset|"
                    "connection failed"
                ),
                1,
            ).otherwise(0),
        )

        .withColumn(
            "is_auth_failure",
            F.when(
                F.lower(
                    F.col("message")
                ).rlike(
                    "authentication failed|"
                    "unauthorized|"
                    "invalid credentials|"
                    "login failed"
                ),
                1,
            ).otherwise(0),
        )
    )

    # ========================================================
    # Remove records with invalid timestamps
    # ========================================================

    logs = logs.filter(
        F.col("event_time").isNotNull()
    )

    # ========================================================
    # One-minute window
    # ========================================================

    logs = logs.withColumn(
        "window",
        F.window(
            F.col("event_time"),
            "1 minute",
        ),
    )

    # ========================================================
    # Aggregate by generic entity
    # ========================================================

    aggregation_expressions = []

    for column in identity_columns:
        aggregation_expressions.append(
            F.first(
                column,
                ignorenulls=True,
            ).alias(column)
        )

    aggregation_expressions.extend(
        [
            F.count("*").alias(
                "total_log_count"
            ),

            F.sum("is_info").alias(
                "info_count"
            ),

            F.sum("is_warn").alias(
                "warning_count"
            ),

            F.sum("is_error").alias(
                "error_count"
            ),

            F.sum("is_http_4xx").alias(
                "http_4xx_count"
            ),

            F.sum("is_http_5xx").alias(
                "http_5xx_count"
            ),

            F.sum("is_timeout").alias(
                "timeout_count"
            ),

            F.sum(
                "is_connection_error"
            ).alias(
                "connection_error_count"
            ),

            F.sum(
                "is_auth_failure"
            ).alias(
                "authentication_failure_count"
            ),

            F.countDistinct(
                F.when(
                    F.col("exception") != "",
                    F.col("exception"),
                )
            ).alias(
                "unique_exception_count"
            ),

            F.countDistinct(
                F.when(
                    F.col("level") == "ERROR",
                    F.col("message"),
                )
            ).alias(
                "unique_error_message_count"
            ),
        ]
    )

    features = (
        logs
        .groupBy(
            "entity_id",
            "window",
        )
        .agg(
            *aggregation_expressions
        )
    )

    # ========================================================
    # Window timestamp
    # ========================================================

    features = (
        features
        .withColumn(
            "timestamp",
            F.col("window.start"),
        )
        .drop("window")
    )

    # ========================================================
    # Rates
    # ========================================================

    features = (
        features

        .withColumn(
            "error_rate",
            F.when(
                F.col("total_log_count") > 0,
                F.col("error_count")
                / F.col("total_log_count"),
            ).otherwise(0.0),
        )

        .withColumn(
            "warning_rate",
            F.when(
                F.col("total_log_count") > 0,
                F.col("warning_count")
                / F.col("total_log_count"),
            ).otherwise(0.0),
        )

        .withColumn(
            "http_5xx_rate",
            F.when(
                F.col("total_log_count") > 0,
                F.col("http_5xx_count")
                / F.col("total_log_count"),
            ).otherwise(0.0),
        )

        .withColumn(
            "timeout_rate",
            F.when(
                F.col("total_log_count") > 0,
                F.col("timeout_count")
                / F.col("total_log_count"),
            ).otherwise(0.0),
        )
    )

    # ========================================================
    # Build final output columns
    # ========================================================

    metadata_columns = [
        "timestamp",
        "entity_id",
    ]

    for column in identity_columns:
        if column not in metadata_columns:
            metadata_columns.append(column)

    feature_columns = [
        "total_log_count",
        "info_count",
        "warning_count",
        "error_count",
        "error_rate",
        "warning_rate",
        "http_4xx_count",
        "http_5xx_count",
        "http_5xx_rate",
        "timeout_count",
        "timeout_rate",
        "connection_error_count",
        "authentication_failure_count",
        "unique_exception_count",
        "unique_error_message_count",
    ]

    final_columns = (
        metadata_columns
        + feature_columns
    )

    features = features.select(
        *final_columns
    )

    # ========================================================
    # Display results
    # ========================================================

    print()
    print("=" * 70)
    print("Generated feature dataset")
    print("=" * 70)

    features.orderBy(
        F.col("timestamp")
    ).show(
        20,
        truncate=False,
    )

    # ========================================================
    # Write per-file feature dataset
    # ========================================================

    print()
    print(
        "Writing feature data to S3..."
    )

    (
        features
        .write
        .mode("overwrite")
        .parquet(spark_output_path)
    )

    print()
    print("=" * 70)
    print("File feature generation completed")
    print("=" * 70)

    print()
    print("Raw input:")
    print(input_path)

    print()
    print("Identity mapping:")
    print(identity_mapping_path)

    print()
    print("Entity priority:")
    print(identity_columns)

    print()
    print("Feature output:")
    print(output_path)

    return output_path


def run(
    input_path: str,
    output_path: str,
):
    """
    Run LogHawk Stage A over a raw S3 folder.

    Example:

        input_path =
            s3://loghawk-data/raw/2026-09-28/

        output_path =
            s3://loghawk-data/features/2026-09-28/

    For every raw file:

        raw/<file>
             |
             +--> identitymapping/identitymapping_<file>.json
             |
             +--> features/<file>/

    Stage A does not start processing a file until its corresponding
    identity mapping exists.

    The function returns only after all files have been processed.
    """

    input_path = normalize_s3_folder(
        input_path
    )

    output_path = normalize_s3_folder(
        output_path
    )

    identity_mapping_folder = (
        derive_identity_mapping_folder(
            input_path
        )
    )
    phase = input_path.rstrip("/").rsplit("/", 1)[-1].upper()
    phase_label = "TRAIN PHASE" if phase == "TRAIN" else "DETECT PHASE"

    fs = create_s3_filesystem()

    raw_files = list_raw_files(
        input_path,
        fs,
    )

    if not raw_files:
        raise RuntimeError(
            "No supported raw log files found in:\n"
            f"{input_path}"
        )

    print()
    print("=" * 70)
    print(f"LogHawk Stage A - {phase_label}")
    print("=" * 70)

    print()
    print("Input folder:")
    print(input_path)

    print()
    print("Identity mapping folder:")
    print(identity_mapping_folder)

    print()
    print("Feature output folder:")
    print(output_path)

    print()
    print(f"Raw files found: {len(raw_files)}")

    for index, path in enumerate(
        raw_files,
        start=1,
    ):
        print(
            f"  {index}. {path}"
        )

    # ========================================================
    # Create ONE Spark session for the complete Stage A run.
    # ========================================================

    spark = (
        SparkSession.builder
        .appName(
            "LogHawk-FeatureEngineering-S3"
        )
        .master("local[1]")
        .config(
            "spark.jars.packages",
            "org.apache.hadoop:hadoop-aws:3.3.4",
        )
        .config(
            "spark.hadoop.fs.s3a.impl",
            "org.apache.hadoop.fs.s3a.S3AFileSystem",
        )
        .config(
            "spark.hadoop.fs.s3a.endpoint",
            config.LH_S3_ENDPOINT,
        )
        .config(
            "spark.hadoop.fs.s3a.access.key",
            config.LH_S3_ACCESS_KEY_ID,
        )
        .config(
            "spark.hadoop.fs.s3a.secret.key",
            config.LH_S3_SECRET_ACCESS_KEY,
        )
        .config(
            "spark.hadoop.fs.s3a.path.style.access",
            "true",
        )
        .config(
            "spark.hadoop.fs.s3a.connection.ssl.enabled",
            "false",
        )
        .config(
            "spark.hadoop.fs.s3a.aws.credentials.provider",
            "org.apache.hadoop.fs.s3a."
            "SimpleAWSCredentialsProvider",
        )
        .config(
            "spark.hadoop.fs.s3a.connection.timeout",
            "60000",
        )
        .config(
            "spark.hadoop.fs.s3a.connection.establish.timeout",
            "60000",
        )
        .config(
            "spark.hadoop.fs.s3a.threads.keepalivetime",
            "60",
        )
        .config(
            "spark.hadoop.fs.s3a.multipart.purge",
            "false",
        )
        .getOrCreate()
    )

    spark.sparkContext.setLogLevel("WARN")

    grouped_files = {}
    for raw_file in raw_files:
        filename = raw_file.rstrip("/").split("/")[-1]
        grouped_files.setdefault(source_group_name(filename), []).append(raw_file)

    print()
    print("Source groups:")
    for group_name, group_files in sorted(grouped_files.items()):
        print(f"  {group_name}: {len(group_files)} file(s)")
        for group_file in group_files:
            print(f"    - {group_file}")

    successful = []
    failed = []
    select_temp_dir = tempfile.mkdtemp(prefix="loghawk-s3-select-")

    try:
        for index, (group_name, group_files) in enumerate(
            sorted(grouped_files.items()), start=1,
        ):
            group_output_path = output_path + group_name + "/"
            print("\n" + "#" * 70)
            print(f"STAGE A GROUP {index} OF {len(grouped_files)}: {group_name}")
            print("#" * 70)
            try:
                normalized = []
                group_identity_columns = None
                for raw_file in group_files:
                    print(f"Reading group member: {raw_file}")
                    file_logs, identity_columns = _read_normalized_file(
                        spark=spark,
                        input_path=raw_file,
                        identity_mapping_folder=identity_mapping_folder,
                        select_temp_dir=select_temp_dir,
                    )
                    if group_identity_columns is None:
                        group_identity_columns = identity_columns
                    elif identity_columns != group_identity_columns:
                        raise ValueError(
                            f"Identity columns differ within source group '{group_name}': "
                            f"{group_identity_columns} vs {identity_columns} ({raw_file})"
                        )
                    normalized.append(file_logs)

                combined_logs = normalized[0]
                for file_logs in normalized[1:]:
                    combined_logs = combined_logs.unionByName(
                        file_logs, allowMissingColumns=True,
                    )

                features = _build_group_features(
                    combined_logs,
                    group_identity_columns or [],
                    group_name,
                )
                spark_output_path = to_spark_s3_path(group_output_path)
                print(f"Writing grouped features to: {group_output_path}")
                features.write.mode("overwrite").parquet(spark_output_path)
                successful.append(group_name)

            except Exception as exc:
                print()
                print(f"ERROR processing source group '{group_name}':")
                print(exc)
                failed.append((group_name, str(exc)))

        # ====================================================
        # Final Stage A status
        # ====================================================

        print()
        print("=" * 70)
        print(f"LogHawk Stage A - {phase_label} Completed")
        print("=" * 70)

        print(
            f"Total files:      {len(raw_files)}"
        )
        print(
            f"Source groups:    {len(grouped_files)}"
        )

        print(
            f"Successful:       {len(successful)}"
        )

        print(
            f"Failed:           {len(failed)}"
        )

        if failed:
            print()
            print("Failed source groups:")

            for path, error in failed:
                print()
                print(path)
                print(f"  {error}")

            raise RuntimeError(
                f"Stage A failed for "
                f"{len(failed)} source group(s)."
            )

        print()
        print(
            "All raw files were successfully processed."
        )

        print()
        print(
            "Feature output folder:"
        )
        print(
            output_path
        )

        return output_path

    finally:
        spark.stop()
        shutil.rmtree(select_temp_dir, ignore_errors=True)


# ============================================================
# Standalone execution
# ============================================================

if __name__ == "__main__":

    INPUT_PATH = (
        "s3://loghawk-data/raw/2026-09-28/"
    )

    OUTPUT_PATH = (
        "s3://loghawk-data/features/2026-09-28/"
    )

    run(
        input_path=INPUT_PATH,
        output_path=OUTPUT_PATH,
    )

